/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ArcHTTPValidationError } from '../models';
// @ts-ignore
import type { DashboardOverviewResponse } from '../models';
/**
 * AnalyticsApi - axios parameter creator
 * @export
 */
export const AnalyticsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * GET /analytics/agent-actions — Individual agent action audit rows.
         * @summary Agent Action Audit
         * @param {string} xAPIKey 
         * @param {string} [agentType] 
         * @param {string} [caseId] 
         * @param {number} [limit] 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentActionAuditV1: async (xAPIKey: string, agentType?: string, caseId?: string, limit?: number, xTenantId?: string, xOrgId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xAPIKey' is not null or undefined
            assertParamExists('agentActionAuditV1', 'xAPIKey', xAPIKey)
            const localVarPath = `/v1/arc/analytics/agent-actions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (agentType !== undefined) {
                localVarQueryParameter['agent_type'] = agentType;
            }

            if (caseId !== undefined) {
                localVarQueryParameter['case_id'] = caseId;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (xTenantId != null) {
                localVarHeaderParameter['X-Tenant-Id'] = String(xTenantId);
            }
            if (xOrgId != null) {
                localVarHeaderParameter['X-Org-Id'] = String(xOrgId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * GET /analytics/agent-performance — Agent performance metrics.
         * @summary Agent Performance
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentPerformanceV1: async (xAPIKey: string, xTenantId?: string, xOrgId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xAPIKey' is not null or undefined
            assertParamExists('agentPerformanceV1', 'xAPIKey', xAPIKey)
            const localVarPath = `/v1/arc/analytics/agent-performance`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (xTenantId != null) {
                localVarHeaderParameter['X-Tenant-Id'] = String(xTenantId);
            }
            if (xOrgId != null) {
                localVarHeaderParameter['X-Org-Id'] = String(xOrgId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * GET /analytics/aging — Aging bucket distribution of outstanding AR.
         * @summary Aging Report
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agingReport: async (xAPIKey: string, xTenantId?: string, xOrgId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xAPIKey' is not null or undefined
            assertParamExists('agingReport', 'xAPIKey', xAPIKey)
            const localVarPath = `/v1/arc/analytics/aging`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (xTenantId != null) {
                localVarHeaderParameter['X-Tenant-Id'] = String(xTenantId);
            }
            if (xOrgId != null) {
                localVarHeaderParameter['X-Org-Id'] = String(xOrgId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * GET /analytics/aging/trend — Historical aging trend (last N days).
         * @summary Aging Trend
         * @param {string} xAPIKey 
         * @param {number} [days] 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agingTrend: async (xAPIKey: string, days?: number, xTenantId?: string, xOrgId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xAPIKey' is not null or undefined
            assertParamExists('agingTrend', 'xAPIKey', xAPIKey)
            const localVarPath = `/v1/arc/analytics/aging/trend`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (days !== undefined) {
                localVarQueryParameter['days'] = days;
            }


    
            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (xTenantId != null) {
                localVarHeaderParameter['X-Tenant-Id'] = String(xTenantId);
            }
            if (xOrgId != null) {
                localVarHeaderParameter['X-Org-Id'] = String(xOrgId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * GET /analytics/cei — Collection Effectiveness Index.
         * @summary Cei Report
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ceiReport: async (xAPIKey: string, xTenantId?: string, xOrgId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xAPIKey' is not null or undefined
            assertParamExists('ceiReport', 'xAPIKey', xAPIKey)
            const localVarPath = `/v1/arc/analytics/cei`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (xTenantId != null) {
                localVarHeaderParameter['X-Tenant-Id'] = String(xTenantId);
            }
            if (xOrgId != null) {
                localVarHeaderParameter['X-Org-Id'] = String(xOrgId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * POST /analytics/aging/snapshot — Manually capture an aging snapshot.
         * @summary Create Aging Snapshot
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAgingSnapshot: async (xAPIKey: string, xTenantId?: string, xOrgId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xAPIKey' is not null or undefined
            assertParamExists('createAgingSnapshot', 'xAPIKey', xAPIKey)
            const localVarPath = `/v1/arc/analytics/aging/snapshot`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (xTenantId != null) {
                localVarHeaderParameter['X-Tenant-Id'] = String(xTenantId);
            }
            if (xOrgId != null) {
                localVarHeaderParameter['X-Org-Id'] = String(xOrgId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * GET /analytics/overview — Combined dashboard analytics payload.
         * @summary Dashboard Overview
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardOverview: async (xAPIKey: string, xTenantId?: string, xOrgId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xAPIKey' is not null or undefined
            assertParamExists('dashboardOverview', 'xAPIKey', xAPIKey)
            const localVarPath = `/v1/arc/analytics/overview`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (xTenantId != null) {
                localVarHeaderParameter['X-Tenant-Id'] = String(xTenantId);
            }
            if (xOrgId != null) {
                localVarHeaderParameter['X-Org-Id'] = String(xOrgId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * GET /analytics/dispute-summary — Dispute statistics.
         * @summary Dispute Summary
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        disputeSummaryV1: async (xAPIKey: string, xTenantId?: string, xOrgId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xAPIKey' is not null or undefined
            assertParamExists('disputeSummaryV1', 'xAPIKey', xAPIKey)
            const localVarPath = `/v1/arc/analytics/dispute-summary`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (xTenantId != null) {
                localVarHeaderParameter['X-Tenant-Id'] = String(xTenantId);
            }
            if (xOrgId != null) {
                localVarHeaderParameter['X-Org-Id'] = String(xOrgId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * GET /analytics/dso — Days Sales Outstanding calculation.
         * @summary Dso Report
         * @param {string} xAPIKey 
         * @param {number} [periodDays] 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dsoReport: async (xAPIKey: string, periodDays?: number, xTenantId?: string, xOrgId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xAPIKey' is not null or undefined
            assertParamExists('dsoReport', 'xAPIKey', xAPIKey)
            const localVarPath = `/v1/arc/analytics/dso`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (periodDays !== undefined) {
                localVarQueryParameter['period_days'] = periodDays;
            }


    
            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (xTenantId != null) {
                localVarHeaderParameter['X-Tenant-Id'] = String(xTenantId);
            }
            if (xOrgId != null) {
                localVarHeaderParameter['X-Org-Id'] = String(xOrgId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * GET /analytics/ptp-summary — Promise-to-Pay statistics.
         * @summary Ptp Summary
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ptpSummaryV1: async (xAPIKey: string, xTenantId?: string, xOrgId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xAPIKey' is not null or undefined
            assertParamExists('ptpSummaryV1', 'xAPIKey', xAPIKey)
            const localVarPath = `/v1/arc/analytics/ptp-summary`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (xTenantId != null) {
                localVarHeaderParameter['X-Tenant-Id'] = String(xTenantId);
            }
            if (xOrgId != null) {
                localVarHeaderParameter['X-Org-Id'] = String(xOrgId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AnalyticsApi - functional programming interface
 * @export
 */
export const AnalyticsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AnalyticsApiAxiosParamCreator(configuration)
    return {
        /**
         * GET /analytics/agent-actions — Individual agent action audit rows.
         * @summary Agent Action Audit
         * @param {string} xAPIKey 
         * @param {string} [agentType] 
         * @param {string} [caseId] 
         * @param {number} [limit] 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentActionAuditV1(xAPIKey: string, agentType?: string, caseId?: string, limit?: number, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentActionAuditV1(xAPIKey, agentType, caseId, limit, xTenantId, xOrgId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AnalyticsApi.agentActionAuditV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * GET /analytics/agent-performance — Agent performance metrics.
         * @summary Agent Performance
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentPerformanceV1(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentPerformanceV1(xAPIKey, xTenantId, xOrgId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AnalyticsApi.agentPerformanceV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * GET /analytics/aging — Aging bucket distribution of outstanding AR.
         * @summary Aging Report
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agingReport(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agingReport(xAPIKey, xTenantId, xOrgId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AnalyticsApi.agingReport']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * GET /analytics/aging/trend — Historical aging trend (last N days).
         * @summary Aging Trend
         * @param {string} xAPIKey 
         * @param {number} [days] 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agingTrend(xAPIKey: string, days?: number, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agingTrend(xAPIKey, days, xTenantId, xOrgId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AnalyticsApi.agingTrend']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * GET /analytics/cei — Collection Effectiveness Index.
         * @summary Cei Report
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ceiReport(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ceiReport(xAPIKey, xTenantId, xOrgId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AnalyticsApi.ceiReport']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * POST /analytics/aging/snapshot — Manually capture an aging snapshot.
         * @summary Create Aging Snapshot
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAgingSnapshot(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createAgingSnapshot(xAPIKey, xTenantId, xOrgId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AnalyticsApi.createAgingSnapshot']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * GET /analytics/overview — Combined dashboard analytics payload.
         * @summary Dashboard Overview
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dashboardOverview(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DashboardOverviewResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dashboardOverview(xAPIKey, xTenantId, xOrgId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AnalyticsApi.dashboardOverview']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * GET /analytics/dispute-summary — Dispute statistics.
         * @summary Dispute Summary
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async disputeSummaryV1(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.disputeSummaryV1(xAPIKey, xTenantId, xOrgId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AnalyticsApi.disputeSummaryV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * GET /analytics/dso — Days Sales Outstanding calculation.
         * @summary Dso Report
         * @param {string} xAPIKey 
         * @param {number} [periodDays] 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dsoReport(xAPIKey: string, periodDays?: number, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dsoReport(xAPIKey, periodDays, xTenantId, xOrgId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AnalyticsApi.dsoReport']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * GET /analytics/ptp-summary — Promise-to-Pay statistics.
         * @summary Ptp Summary
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ptpSummaryV1(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ptpSummaryV1(xAPIKey, xTenantId, xOrgId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AnalyticsApi.ptpSummaryV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AnalyticsApi - factory interface
 * @export
 */
export const AnalyticsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AnalyticsApiFp(configuration)
    return {
        /**
         * GET /analytics/agent-actions — Individual agent action audit rows.
         * @summary Agent Action Audit
         * @param {string} xAPIKey 
         * @param {string} [agentType] 
         * @param {string} [caseId] 
         * @param {number} [limit] 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentActionAuditV1(xAPIKey: string, agentType?: string, caseId?: string, limit?: number, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.agentActionAuditV1(xAPIKey, agentType, caseId, limit, xTenantId, xOrgId, options).then((request) => request(axios, basePath));
        },
        /**
         * GET /analytics/agent-performance — Agent performance metrics.
         * @summary Agent Performance
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentPerformanceV1(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.agentPerformanceV1(xAPIKey, xTenantId, xOrgId, options).then((request) => request(axios, basePath));
        },
        /**
         * GET /analytics/aging — Aging bucket distribution of outstanding AR.
         * @summary Aging Report
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agingReport(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.agingReport(xAPIKey, xTenantId, xOrgId, options).then((request) => request(axios, basePath));
        },
        /**
         * GET /analytics/aging/trend — Historical aging trend (last N days).
         * @summary Aging Trend
         * @param {string} xAPIKey 
         * @param {number} [days] 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agingTrend(xAPIKey: string, days?: number, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.agingTrend(xAPIKey, days, xTenantId, xOrgId, options).then((request) => request(axios, basePath));
        },
        /**
         * GET /analytics/cei — Collection Effectiveness Index.
         * @summary Cei Report
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ceiReport(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.ceiReport(xAPIKey, xTenantId, xOrgId, options).then((request) => request(axios, basePath));
        },
        /**
         * POST /analytics/aging/snapshot — Manually capture an aging snapshot.
         * @summary Create Aging Snapshot
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAgingSnapshot(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.createAgingSnapshot(xAPIKey, xTenantId, xOrgId, options).then((request) => request(axios, basePath));
        },
        /**
         * GET /analytics/overview — Combined dashboard analytics payload.
         * @summary Dashboard Overview
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardOverview(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<DashboardOverviewResponse> {
            return localVarFp.dashboardOverview(xAPIKey, xTenantId, xOrgId, options).then((request) => request(axios, basePath));
        },
        /**
         * GET /analytics/dispute-summary — Dispute statistics.
         * @summary Dispute Summary
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        disputeSummaryV1(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.disputeSummaryV1(xAPIKey, xTenantId, xOrgId, options).then((request) => request(axios, basePath));
        },
        /**
         * GET /analytics/dso — Days Sales Outstanding calculation.
         * @summary Dso Report
         * @param {string} xAPIKey 
         * @param {number} [periodDays] 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dsoReport(xAPIKey: string, periodDays?: number, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.dsoReport(xAPIKey, periodDays, xTenantId, xOrgId, options).then((request) => request(axios, basePath));
        },
        /**
         * GET /analytics/ptp-summary — Promise-to-Pay statistics.
         * @summary Ptp Summary
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ptpSummaryV1(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.ptpSummaryV1(xAPIKey, xTenantId, xOrgId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AnalyticsApi - interface
 * @export
 * @interface AnalyticsApi
 */
export interface AnalyticsApiInterface {
    /**
     * GET /analytics/agent-actions — Individual agent action audit rows.
     * @summary Agent Action Audit
     * @param {string} xAPIKey 
     * @param {string} [agentType] 
     * @param {string} [caseId] 
     * @param {number} [limit] 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalyticsApiInterface
     */
    agentActionAuditV1(xAPIKey: string, agentType?: string, caseId?: string, limit?: number, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * GET /analytics/agent-performance — Agent performance metrics.
     * @summary Agent Performance
     * @param {string} xAPIKey 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalyticsApiInterface
     */
    agentPerformanceV1(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * GET /analytics/aging — Aging bucket distribution of outstanding AR.
     * @summary Aging Report
     * @param {string} xAPIKey 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalyticsApiInterface
     */
    agingReport(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * GET /analytics/aging/trend — Historical aging trend (last N days).
     * @summary Aging Trend
     * @param {string} xAPIKey 
     * @param {number} [days] 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalyticsApiInterface
     */
    agingTrend(xAPIKey: string, days?: number, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * GET /analytics/cei — Collection Effectiveness Index.
     * @summary Cei Report
     * @param {string} xAPIKey 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalyticsApiInterface
     */
    ceiReport(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * POST /analytics/aging/snapshot — Manually capture an aging snapshot.
     * @summary Create Aging Snapshot
     * @param {string} xAPIKey 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalyticsApiInterface
     */
    createAgingSnapshot(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * GET /analytics/overview — Combined dashboard analytics payload.
     * @summary Dashboard Overview
     * @param {string} xAPIKey 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalyticsApiInterface
     */
    dashboardOverview(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<DashboardOverviewResponse>;

    /**
     * GET /analytics/dispute-summary — Dispute statistics.
     * @summary Dispute Summary
     * @param {string} xAPIKey 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalyticsApiInterface
     */
    disputeSummaryV1(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * GET /analytics/dso — Days Sales Outstanding calculation.
     * @summary Dso Report
     * @param {string} xAPIKey 
     * @param {number} [periodDays] 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalyticsApiInterface
     */
    dsoReport(xAPIKey: string, periodDays?: number, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * GET /analytics/ptp-summary — Promise-to-Pay statistics.
     * @summary Ptp Summary
     * @param {string} xAPIKey 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalyticsApiInterface
     */
    ptpSummaryV1(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any>;

}

/**
 * AnalyticsApi - object-oriented interface
 * @export
 * @class AnalyticsApi
 * @extends {BaseAPI}
 */
export class AnalyticsApi extends BaseAPI implements AnalyticsApiInterface {
    /**
     * GET /analytics/agent-actions — Individual agent action audit rows.
     * @summary Agent Action Audit
     * @param {string} xAPIKey 
     * @param {string} [agentType] 
     * @param {string} [caseId] 
     * @param {number} [limit] 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalyticsApi
     */
    public agentActionAuditV1(xAPIKey: string, agentType?: string, caseId?: string, limit?: number, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig) {
        return AnalyticsApiFp(this.configuration).agentActionAuditV1(xAPIKey, agentType, caseId, limit, xTenantId, xOrgId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * GET /analytics/agent-performance — Agent performance metrics.
     * @summary Agent Performance
     * @param {string} xAPIKey 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalyticsApi
     */
    public agentPerformanceV1(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig) {
        return AnalyticsApiFp(this.configuration).agentPerformanceV1(xAPIKey, xTenantId, xOrgId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * GET /analytics/aging — Aging bucket distribution of outstanding AR.
     * @summary Aging Report
     * @param {string} xAPIKey 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalyticsApi
     */
    public agingReport(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig) {
        return AnalyticsApiFp(this.configuration).agingReport(xAPIKey, xTenantId, xOrgId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * GET /analytics/aging/trend — Historical aging trend (last N days).
     * @summary Aging Trend
     * @param {string} xAPIKey 
     * @param {number} [days] 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalyticsApi
     */
    public agingTrend(xAPIKey: string, days?: number, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig) {
        return AnalyticsApiFp(this.configuration).agingTrend(xAPIKey, days, xTenantId, xOrgId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * GET /analytics/cei — Collection Effectiveness Index.
     * @summary Cei Report
     * @param {string} xAPIKey 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalyticsApi
     */
    public ceiReport(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig) {
        return AnalyticsApiFp(this.configuration).ceiReport(xAPIKey, xTenantId, xOrgId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * POST /analytics/aging/snapshot — Manually capture an aging snapshot.
     * @summary Create Aging Snapshot
     * @param {string} xAPIKey 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalyticsApi
     */
    public createAgingSnapshot(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig) {
        return AnalyticsApiFp(this.configuration).createAgingSnapshot(xAPIKey, xTenantId, xOrgId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * GET /analytics/overview — Combined dashboard analytics payload.
     * @summary Dashboard Overview
     * @param {string} xAPIKey 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalyticsApi
     */
    public dashboardOverview(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig) {
        return AnalyticsApiFp(this.configuration).dashboardOverview(xAPIKey, xTenantId, xOrgId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * GET /analytics/dispute-summary — Dispute statistics.
     * @summary Dispute Summary
     * @param {string} xAPIKey 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalyticsApi
     */
    public disputeSummaryV1(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig) {
        return AnalyticsApiFp(this.configuration).disputeSummaryV1(xAPIKey, xTenantId, xOrgId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * GET /analytics/dso — Days Sales Outstanding calculation.
     * @summary Dso Report
     * @param {string} xAPIKey 
     * @param {number} [periodDays] 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalyticsApi
     */
    public dsoReport(xAPIKey: string, periodDays?: number, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig) {
        return AnalyticsApiFp(this.configuration).dsoReport(xAPIKey, periodDays, xTenantId, xOrgId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * GET /analytics/ptp-summary — Promise-to-Pay statistics.
     * @summary Ptp Summary
     * @param {string} xAPIKey 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalyticsApi
     */
    public ptpSummaryV1(xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig) {
        return AnalyticsApiFp(this.configuration).ptpSummaryV1(xAPIKey, xTenantId, xOrgId, options).then((request) => request(this.axios, this.basePath));
    }
}

