/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.3.0-rc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BuyerAcceptRequest } from '../models';
// @ts-ignore
import type { BuyerOtpRequestResponse } from '../models';
// @ts-ignore
import type { BuyerOtpVerifyRequest } from '../models';
// @ts-ignore
import type { BuyerOtpVerifyResponse } from '../models';
// @ts-ignore
import type { BuyerQuoteProjection } from '../models';
// @ts-ignore
import type { BuyerRejectRequest } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
/**
 * BuyerQuotesApi - axios parameter creator
 * @export
 */
export const BuyerQuotesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Accept Buyer Quote
         * @param {BuyerAcceptRequest} buyerAcceptRequest 
         * @param {string} [idempotencyKey] 
         * @param {string} [xQuoteBuyerToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        acceptBuyerQuote: async (buyerAcceptRequest: BuyerAcceptRequest, idempotencyKey?: string, xQuoteBuyerToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'buyerAcceptRequest' is not null or undefined
            assertParamExists('acceptBuyerQuote', 'buyerAcceptRequest', buyerAcceptRequest)
            const localVarPath = `/v1/buyer/quotes/accept`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            if (xQuoteBuyerToken != null) {
                localVarHeaderParameter['X-Quote-Buyer-Token'] = String(xQuoteBuyerToken);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(buyerAcceptRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Buyer Quote
         * @param {string} [xQuoteBuyerToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBuyerQuote: async (xQuoteBuyerToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/buyer/quotes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xQuoteBuyerToken != null) {
                localVarHeaderParameter['X-Quote-Buyer-Token'] = String(xQuoteBuyerToken);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Reject Buyer Quote
         * @param {BuyerRejectRequest} buyerRejectRequest 
         * @param {string} [xQuoteBuyerToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rejectBuyerQuote: async (buyerRejectRequest: BuyerRejectRequest, xQuoteBuyerToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'buyerRejectRequest' is not null or undefined
            assertParamExists('rejectBuyerQuote', 'buyerRejectRequest', buyerRejectRequest)
            const localVarPath = `/v1/buyer/quotes/reject`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xQuoteBuyerToken != null) {
                localVarHeaderParameter['X-Quote-Buyer-Token'] = String(xQuoteBuyerToken);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(buyerRejectRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Request Otp
         * @param {string} [xQuoteBuyerToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestOtp: async (xQuoteBuyerToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/buyer/quotes/otp`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xQuoteBuyerToken != null) {
                localVarHeaderParameter['X-Quote-Buyer-Token'] = String(xQuoteBuyerToken);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Verify Otp
         * @param {BuyerOtpVerifyRequest} buyerOtpVerifyRequest 
         * @param {string} [xQuoteBuyerToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyOtp: async (buyerOtpVerifyRequest: BuyerOtpVerifyRequest, xQuoteBuyerToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'buyerOtpVerifyRequest' is not null or undefined
            assertParamExists('verifyOtp', 'buyerOtpVerifyRequest', buyerOtpVerifyRequest)
            const localVarPath = `/v1/buyer/quotes/otp/verify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xQuoteBuyerToken != null) {
                localVarHeaderParameter['X-Quote-Buyer-Token'] = String(xQuoteBuyerToken);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(buyerOtpVerifyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BuyerQuotesApi - functional programming interface
 * @export
 */
export const BuyerQuotesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BuyerQuotesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Accept Buyer Quote
         * @param {BuyerAcceptRequest} buyerAcceptRequest 
         * @param {string} [idempotencyKey] 
         * @param {string} [xQuoteBuyerToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async acceptBuyerQuote(buyerAcceptRequest: BuyerAcceptRequest, idempotencyKey?: string, xQuoteBuyerToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.acceptBuyerQuote(buyerAcceptRequest, idempotencyKey, xQuoteBuyerToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BuyerQuotesApi.acceptBuyerQuote']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Buyer Quote
         * @param {string} [xQuoteBuyerToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBuyerQuote(xQuoteBuyerToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BuyerQuoteProjection>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBuyerQuote(xQuoteBuyerToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BuyerQuotesApi.getBuyerQuote']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Reject Buyer Quote
         * @param {BuyerRejectRequest} buyerRejectRequest 
         * @param {string} [xQuoteBuyerToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rejectBuyerQuote(buyerRejectRequest: BuyerRejectRequest, xQuoteBuyerToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rejectBuyerQuote(buyerRejectRequest, xQuoteBuyerToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BuyerQuotesApi.rejectBuyerQuote']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Request Otp
         * @param {string} [xQuoteBuyerToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async requestOtp(xQuoteBuyerToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BuyerOtpRequestResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.requestOtp(xQuoteBuyerToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BuyerQuotesApi.requestOtp']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Verify Otp
         * @param {BuyerOtpVerifyRequest} buyerOtpVerifyRequest 
         * @param {string} [xQuoteBuyerToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async verifyOtp(buyerOtpVerifyRequest: BuyerOtpVerifyRequest, xQuoteBuyerToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BuyerOtpVerifyResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.verifyOtp(buyerOtpVerifyRequest, xQuoteBuyerToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BuyerQuotesApi.verifyOtp']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BuyerQuotesApi - factory interface
 * @export
 */
export const BuyerQuotesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BuyerQuotesApiFp(configuration)
    return {
        /**
         * 
         * @summary Accept Buyer Quote
         * @param {BuyerAcceptRequest} buyerAcceptRequest 
         * @param {string} [idempotencyKey] 
         * @param {string} [xQuoteBuyerToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        acceptBuyerQuote(buyerAcceptRequest: BuyerAcceptRequest, idempotencyKey?: string, xQuoteBuyerToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.acceptBuyerQuote(buyerAcceptRequest, idempotencyKey, xQuoteBuyerToken, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Buyer Quote
         * @param {string} [xQuoteBuyerToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBuyerQuote(xQuoteBuyerToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<BuyerQuoteProjection> {
            return localVarFp.getBuyerQuote(xQuoteBuyerToken, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Reject Buyer Quote
         * @param {BuyerRejectRequest} buyerRejectRequest 
         * @param {string} [xQuoteBuyerToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rejectBuyerQuote(buyerRejectRequest: BuyerRejectRequest, xQuoteBuyerToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.rejectBuyerQuote(buyerRejectRequest, xQuoteBuyerToken, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Request Otp
         * @param {string} [xQuoteBuyerToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestOtp(xQuoteBuyerToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<BuyerOtpRequestResponse> {
            return localVarFp.requestOtp(xQuoteBuyerToken, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Verify Otp
         * @param {BuyerOtpVerifyRequest} buyerOtpVerifyRequest 
         * @param {string} [xQuoteBuyerToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyOtp(buyerOtpVerifyRequest: BuyerOtpVerifyRequest, xQuoteBuyerToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<BuyerOtpVerifyResponse> {
            return localVarFp.verifyOtp(buyerOtpVerifyRequest, xQuoteBuyerToken, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BuyerQuotesApi - interface
 * @export
 * @interface BuyerQuotesApi
 */
export interface BuyerQuotesApiInterface {
    /**
     * 
     * @summary Accept Buyer Quote
     * @param {BuyerAcceptRequest} buyerAcceptRequest 
     * @param {string} [idempotencyKey] 
     * @param {string} [xQuoteBuyerToken] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BuyerQuotesApiInterface
     */
    acceptBuyerQuote(buyerAcceptRequest: BuyerAcceptRequest, idempotencyKey?: string, xQuoteBuyerToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }>;

    /**
     * 
     * @summary Get Buyer Quote
     * @param {string} [xQuoteBuyerToken] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BuyerQuotesApiInterface
     */
    getBuyerQuote(xQuoteBuyerToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<BuyerQuoteProjection>;

    /**
     * 
     * @summary Reject Buyer Quote
     * @param {BuyerRejectRequest} buyerRejectRequest 
     * @param {string} [xQuoteBuyerToken] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BuyerQuotesApiInterface
     */
    rejectBuyerQuote(buyerRejectRequest: BuyerRejectRequest, xQuoteBuyerToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }>;

    /**
     * 
     * @summary Request Otp
     * @param {string} [xQuoteBuyerToken] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BuyerQuotesApiInterface
     */
    requestOtp(xQuoteBuyerToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<BuyerOtpRequestResponse>;

    /**
     * 
     * @summary Verify Otp
     * @param {BuyerOtpVerifyRequest} buyerOtpVerifyRequest 
     * @param {string} [xQuoteBuyerToken] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BuyerQuotesApiInterface
     */
    verifyOtp(buyerOtpVerifyRequest: BuyerOtpVerifyRequest, xQuoteBuyerToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<BuyerOtpVerifyResponse>;

}

/**
 * BuyerQuotesApi - object-oriented interface
 * @export
 * @class BuyerQuotesApi
 * @extends {BaseAPI}
 */
export class BuyerQuotesApi extends BaseAPI implements BuyerQuotesApiInterface {
    /**
     * 
     * @summary Accept Buyer Quote
     * @param {BuyerAcceptRequest} buyerAcceptRequest 
     * @param {string} [idempotencyKey] 
     * @param {string} [xQuoteBuyerToken] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BuyerQuotesApi
     */
    public acceptBuyerQuote(buyerAcceptRequest: BuyerAcceptRequest, idempotencyKey?: string, xQuoteBuyerToken?: string, options?: RawAxiosRequestConfig) {
        return BuyerQuotesApiFp(this.configuration).acceptBuyerQuote(buyerAcceptRequest, idempotencyKey, xQuoteBuyerToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Buyer Quote
     * @param {string} [xQuoteBuyerToken] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BuyerQuotesApi
     */
    public getBuyerQuote(xQuoteBuyerToken?: string, options?: RawAxiosRequestConfig) {
        return BuyerQuotesApiFp(this.configuration).getBuyerQuote(xQuoteBuyerToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Reject Buyer Quote
     * @param {BuyerRejectRequest} buyerRejectRequest 
     * @param {string} [xQuoteBuyerToken] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BuyerQuotesApi
     */
    public rejectBuyerQuote(buyerRejectRequest: BuyerRejectRequest, xQuoteBuyerToken?: string, options?: RawAxiosRequestConfig) {
        return BuyerQuotesApiFp(this.configuration).rejectBuyerQuote(buyerRejectRequest, xQuoteBuyerToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Request Otp
     * @param {string} [xQuoteBuyerToken] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BuyerQuotesApi
     */
    public requestOtp(xQuoteBuyerToken?: string, options?: RawAxiosRequestConfig) {
        return BuyerQuotesApiFp(this.configuration).requestOtp(xQuoteBuyerToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Verify Otp
     * @param {BuyerOtpVerifyRequest} buyerOtpVerifyRequest 
     * @param {string} [xQuoteBuyerToken] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BuyerQuotesApi
     */
    public verifyOtp(buyerOtpVerifyRequest: BuyerOtpVerifyRequest, xQuoteBuyerToken?: string, options?: RawAxiosRequestConfig) {
        return BuyerQuotesApiFp(this.configuration).verifyOtp(buyerOtpVerifyRequest, xQuoteBuyerToken, options).then((request) => request(this.axios, this.basePath));
    }
}

