/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Event } from '../models';
// @ts-ignore
import type { IngestEventsBody } from '../models';
// @ts-ignore
import type { IngestedEvent } from '../models';
// @ts-ignore
import type { IngestedEventCursorPaginatedResponse } from '../models';
// @ts-ignore
import type { ListEventsV2FilterParam } from '../models';
// @ts-ignore
import type { UnexpectedProblemResponse } from '../models';
/**
 * EventsApi - axios parameter creator
 * @export
 */
export const EventsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Ingests an event or batch of events following the CloudEvents specification.
         * @summary Ingest events  
         * @param {Event} event 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingestEvents: async (event: Event, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'event' is not null or undefined
            assertParamExists('ingestEvents', 'event', event)
            const localVarPath = `/api/v1/events`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CloudTokenAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/cloudevents+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(event, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List ingested events within a time range.  If the from query param is not provided it defaults to last 72 hours.
         * @summary List ingested events
         * @param {string} [clientId] Client ID Useful to track progress of a query.
         * @param {string} [ingestedAtFrom] Start date-time in RFC 3339 format.  Inclusive.
         * @param {string} [ingestedAtTo] End date-time in RFC 3339 format.  Inclusive.
         * @param {string} [id] The event ID.  Accepts partial ID.
         * @param {string} [subject] The event subject.  Accepts partial subject.
         * @param {Array<string>} [customerId] The event customer ID.
         * @param {string} [from] Start date-time in RFC 3339 format.  Inclusive.
         * @param {string} [to] End date-time in RFC 3339 format.  Inclusive.
         * @param {number} [limit] Number of events to return.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listEvents: async (clientId?: string, ingestedAtFrom?: string, ingestedAtTo?: string, id?: string, subject?: string, customerId?: Array<string>, from?: string, to?: string, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/events`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CloudTokenAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (clientId !== undefined) {
                localVarQueryParameter['clientId'] = clientId;
            }

            if (ingestedAtFrom !== undefined) {
                localVarQueryParameter['ingestedAtFrom'] = (ingestedAtFrom as any instanceof Date) ?
                    (ingestedAtFrom as any).toISOString() :
                    ingestedAtFrom;
            }

            if (ingestedAtTo !== undefined) {
                localVarQueryParameter['ingestedAtTo'] = (ingestedAtTo as any instanceof Date) ?
                    (ingestedAtTo as any).toISOString() :
                    ingestedAtTo;
            }

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            if (subject !== undefined) {
                localVarQueryParameter['subject'] = subject;
            }

            if (customerId) {
                localVarQueryParameter['customerId'] = customerId;
            }

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString() :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString() :
                    to;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List ingested events with advanced filtering and cursor pagination.
         * @summary List ingested events
         * @param {string} [cursor] The cursor after which to start the pagination.
         * @param {number} [limit] The limit of the pagination.
         * @param {string} [clientId] Client ID Useful to track progress of a query.
         * @param {ListEventsV2FilterParam} [filter] The filter for the events encoded as JSON string.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listEventsV2: async (cursor?: string, limit?: number, clientId?: string, filter?: ListEventsV2FilterParam, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v2/events`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CloudTokenAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (clientId !== undefined) {
                localVarQueryParameter['clientId'] = clientId;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EventsApi - functional programming interface
 * @export
 */
export const EventsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EventsApiAxiosParamCreator(configuration)
    return {
        /**
         * Ingests an event or batch of events following the CloudEvents specification.
         * @summary Ingest events  
         * @param {Event} event 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ingestEvents(event: Event, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ingestEvents(event, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventsApi.ingestEvents']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List ingested events within a time range.  If the from query param is not provided it defaults to last 72 hours.
         * @summary List ingested events
         * @param {string} [clientId] Client ID Useful to track progress of a query.
         * @param {string} [ingestedAtFrom] Start date-time in RFC 3339 format.  Inclusive.
         * @param {string} [ingestedAtTo] End date-time in RFC 3339 format.  Inclusive.
         * @param {string} [id] The event ID.  Accepts partial ID.
         * @param {string} [subject] The event subject.  Accepts partial subject.
         * @param {Array<string>} [customerId] The event customer ID.
         * @param {string} [from] Start date-time in RFC 3339 format.  Inclusive.
         * @param {string} [to] End date-time in RFC 3339 format.  Inclusive.
         * @param {number} [limit] Number of events to return.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listEvents(clientId?: string, ingestedAtFrom?: string, ingestedAtTo?: string, id?: string, subject?: string, customerId?: Array<string>, from?: string, to?: string, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<IngestedEvent>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listEvents(clientId, ingestedAtFrom, ingestedAtTo, id, subject, customerId, from, to, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventsApi.listEvents']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List ingested events with advanced filtering and cursor pagination.
         * @summary List ingested events
         * @param {string} [cursor] The cursor after which to start the pagination.
         * @param {number} [limit] The limit of the pagination.
         * @param {string} [clientId] Client ID Useful to track progress of a query.
         * @param {ListEventsV2FilterParam} [filter] The filter for the events encoded as JSON string.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listEventsV2(cursor?: string, limit?: number, clientId?: string, filter?: ListEventsV2FilterParam, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IngestedEventCursorPaginatedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listEventsV2(cursor, limit, clientId, filter, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventsApi.listEventsV2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EventsApi - factory interface
 * @export
 */
export const EventsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EventsApiFp(configuration)
    return {
        /**
         * Ingests an event or batch of events following the CloudEvents specification.
         * @summary Ingest events  
         * @param {Event} event 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingestEvents(event: Event, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.ingestEvents(event, options).then((request) => request(axios, basePath));
        },
        /**
         * List ingested events within a time range.  If the from query param is not provided it defaults to last 72 hours.
         * @summary List ingested events
         * @param {string} [clientId] Client ID Useful to track progress of a query.
         * @param {string} [ingestedAtFrom] Start date-time in RFC 3339 format.  Inclusive.
         * @param {string} [ingestedAtTo] End date-time in RFC 3339 format.  Inclusive.
         * @param {string} [id] The event ID.  Accepts partial ID.
         * @param {string} [subject] The event subject.  Accepts partial subject.
         * @param {Array<string>} [customerId] The event customer ID.
         * @param {string} [from] Start date-time in RFC 3339 format.  Inclusive.
         * @param {string} [to] End date-time in RFC 3339 format.  Inclusive.
         * @param {number} [limit] Number of events to return.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listEvents(clientId?: string, ingestedAtFrom?: string, ingestedAtTo?: string, id?: string, subject?: string, customerId?: Array<string>, from?: string, to?: string, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<IngestedEvent>> {
            return localVarFp.listEvents(clientId, ingestedAtFrom, ingestedAtTo, id, subject, customerId, from, to, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * List ingested events with advanced filtering and cursor pagination.
         * @summary List ingested events
         * @param {string} [cursor] The cursor after which to start the pagination.
         * @param {number} [limit] The limit of the pagination.
         * @param {string} [clientId] Client ID Useful to track progress of a query.
         * @param {ListEventsV2FilterParam} [filter] The filter for the events encoded as JSON string.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listEventsV2(cursor?: string, limit?: number, clientId?: string, filter?: ListEventsV2FilterParam, options?: RawAxiosRequestConfig): AxiosPromise<IngestedEventCursorPaginatedResponse> {
            return localVarFp.listEventsV2(cursor, limit, clientId, filter, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EventsApi - interface
 * @export
 * @interface EventsApi
 */
export interface EventsApiInterface {
    /**
     * Ingests an event or batch of events following the CloudEvents specification.
     * @summary Ingest events  
     * @param {Event} event 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    ingestEvents(event: Event, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * List ingested events within a time range.  If the from query param is not provided it defaults to last 72 hours.
     * @summary List ingested events
     * @param {string} [clientId] Client ID Useful to track progress of a query.
     * @param {string} [ingestedAtFrom] Start date-time in RFC 3339 format.  Inclusive.
     * @param {string} [ingestedAtTo] End date-time in RFC 3339 format.  Inclusive.
     * @param {string} [id] The event ID.  Accepts partial ID.
     * @param {string} [subject] The event subject.  Accepts partial subject.
     * @param {Array<string>} [customerId] The event customer ID.
     * @param {string} [from] Start date-time in RFC 3339 format.  Inclusive.
     * @param {string} [to] End date-time in RFC 3339 format.  Inclusive.
     * @param {number} [limit] Number of events to return.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    listEvents(clientId?: string, ingestedAtFrom?: string, ingestedAtTo?: string, id?: string, subject?: string, customerId?: Array<string>, from?: string, to?: string, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<IngestedEvent>>;

    /**
     * List ingested events with advanced filtering and cursor pagination.
     * @summary List ingested events
     * @param {string} [cursor] The cursor after which to start the pagination.
     * @param {number} [limit] The limit of the pagination.
     * @param {string} [clientId] Client ID Useful to track progress of a query.
     * @param {ListEventsV2FilterParam} [filter] The filter for the events encoded as JSON string.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApiInterface
     */
    listEventsV2(cursor?: string, limit?: number, clientId?: string, filter?: ListEventsV2FilterParam, options?: RawAxiosRequestConfig): AxiosPromise<IngestedEventCursorPaginatedResponse>;

}

/**
 * EventsApi - object-oriented interface
 * @export
 * @class EventsApi
 * @extends {BaseAPI}
 */
export class EventsApi extends BaseAPI implements EventsApiInterface {
    /**
     * Ingests an event or batch of events following the CloudEvents specification.
     * @summary Ingest events  
     * @param {Event} event 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApi
     */
    public ingestEvents(event: Event, options?: RawAxiosRequestConfig) {
        return EventsApiFp(this.configuration).ingestEvents(event, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List ingested events within a time range.  If the from query param is not provided it defaults to last 72 hours.
     * @summary List ingested events
     * @param {string} [clientId] Client ID Useful to track progress of a query.
     * @param {string} [ingestedAtFrom] Start date-time in RFC 3339 format.  Inclusive.
     * @param {string} [ingestedAtTo] End date-time in RFC 3339 format.  Inclusive.
     * @param {string} [id] The event ID.  Accepts partial ID.
     * @param {string} [subject] The event subject.  Accepts partial subject.
     * @param {Array<string>} [customerId] The event customer ID.
     * @param {string} [from] Start date-time in RFC 3339 format.  Inclusive.
     * @param {string} [to] End date-time in RFC 3339 format.  Inclusive.
     * @param {number} [limit] Number of events to return.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApi
     */
    public listEvents(clientId?: string, ingestedAtFrom?: string, ingestedAtTo?: string, id?: string, subject?: string, customerId?: Array<string>, from?: string, to?: string, limit?: number, options?: RawAxiosRequestConfig) {
        return EventsApiFp(this.configuration).listEvents(clientId, ingestedAtFrom, ingestedAtTo, id, subject, customerId, from, to, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List ingested events with advanced filtering and cursor pagination.
     * @summary List ingested events
     * @param {string} [cursor] The cursor after which to start the pagination.
     * @param {number} [limit] The limit of the pagination.
     * @param {string} [clientId] Client ID Useful to track progress of a query.
     * @param {ListEventsV2FilterParam} [filter] The filter for the events encoded as JSON string.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApi
     */
    public listEventsV2(cursor?: string, limit?: number, clientId?: string, filter?: ListEventsV2FilterParam, options?: RawAxiosRequestConfig) {
        return EventsApiFp(this.configuration).listEventsV2(cursor, limit, clientId, filter, options).then((request) => request(this.axios, this.basePath));
    }
}

