/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AppApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
/**
 * InternalSubscriptionsApi - axios parameter creator
 * @export
 */
export const InternalSubscriptionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Sync Subscription
         * @param {AppApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest} appApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        syncSubscriptionPost: async (appApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest: AppApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'appApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest' is not null or undefined
            assertParamExists('syncSubscriptionPost', 'appApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest', appApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest)
            const localVarPath = `/v1/internal/subscriptions/sync`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(appApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InternalSubscriptionsApi - functional programming interface
 * @export
 */
export const InternalSubscriptionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InternalSubscriptionsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Sync Subscription
         * @param {AppApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest} appApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async syncSubscriptionPost(appApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest: AppApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.syncSubscriptionPost(appApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InternalSubscriptionsApi.syncSubscriptionPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InternalSubscriptionsApi - factory interface
 * @export
 */
export const InternalSubscriptionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InternalSubscriptionsApiFp(configuration)
    return {
        /**
         * 
         * @summary Sync Subscription
         * @param {AppApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest} appApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        syncSubscriptionPost(appApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest: AppApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.syncSubscriptionPost(appApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest, authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InternalSubscriptionsApi - interface
 * @export
 * @interface InternalSubscriptionsApi
 */
export interface InternalSubscriptionsApiInterface {
    /**
     * 
     * @summary Sync Subscription
     * @param {AppApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest} appApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InternalSubscriptionsApiInterface
     */
    syncSubscriptionPost(appApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest: AppApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<any>;

}

/**
 * InternalSubscriptionsApi - object-oriented interface
 * @export
 * @class InternalSubscriptionsApi
 * @extends {BaseAPI}
 */
export class InternalSubscriptionsApi extends BaseAPI implements InternalSubscriptionsApiInterface {
    /**
     * 
     * @summary Sync Subscription
     * @param {AppApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest} appApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InternalSubscriptionsApi
     */
    public syncSubscriptionPost(appApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest: AppApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest, authorization?: string, options?: RawAxiosRequestConfig) {
        return InternalSubscriptionsApiFp(this.configuration).syncSubscriptionPost(appApiV1InternalSubscriptionSyncSchemasSubscriptionSyncRequest, authorization, options).then((request) => request(this.axios, this.basePath));
    }
}

