/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HTTPValidationError } from '../models';
/**
 * MoometerProxyApi - axios parameter creator
 * @export
 */
export const MoometerProxyApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
         * @summary Proxy Openmeter
         * @param {string} path 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        proxyOpenmeter: async (path: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'path' is not null or undefined
            assertParamExists('proxyOpenmeter', 'path', path)
            const localVarPath = `/v1/moometer/{path}`
                .replace(`{${"path"}}`, encodeURIComponent(String(path)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
         * @summary Proxy Openmeter
         * @param {string} path 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        proxyOpenmeter_1: async (path: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'path' is not null or undefined
            assertParamExists('proxyOpenmeter_1', 'path', path)
            const localVarPath = `/v1/moometer/{path}`
                .replace(`{${"path"}}`, encodeURIComponent(String(path)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
         * @summary Proxy Openmeter
         * @param {string} path 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        proxyOpenmeter_2: async (path: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'path' is not null or undefined
            assertParamExists('proxyOpenmeter_2', 'path', path)
            const localVarPath = `/v1/moometer/{path}`
                .replace(`{${"path"}}`, encodeURIComponent(String(path)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
         * @summary Proxy Openmeter
         * @param {string} path 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        proxyOpenmeter_3: async (path: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'path' is not null or undefined
            assertParamExists('proxyOpenmeter_3', 'path', path)
            const localVarPath = `/v1/moometer/{path}`
                .replace(`{${"path"}}`, encodeURIComponent(String(path)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
         * @summary Proxy Openmeter
         * @param {string} path 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        proxyOpenmeter_4: async (path: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'path' is not null or undefined
            assertParamExists('proxyOpenmeter_4', 'path', path)
            const localVarPath = `/v1/moometer/{path}`
                .replace(`{${"path"}}`, encodeURIComponent(String(path)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MoometerProxyApi - functional programming interface
 * @export
 */
export const MoometerProxyApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MoometerProxyApiAxiosParamCreator(configuration)
    return {
        /**
         * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
         * @summary Proxy Openmeter
         * @param {string} path 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async proxyOpenmeter(path: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.proxyOpenmeter(path, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MoometerProxyApi.proxyOpenmeter']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
         * @summary Proxy Openmeter
         * @param {string} path 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async proxyOpenmeter_1(path: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.proxyOpenmeter_1(path, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MoometerProxyApi.proxyOpenmeter_1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
         * @summary Proxy Openmeter
         * @param {string} path 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async proxyOpenmeter_2(path: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.proxyOpenmeter_2(path, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MoometerProxyApi.proxyOpenmeter_2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
         * @summary Proxy Openmeter
         * @param {string} path 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async proxyOpenmeter_3(path: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.proxyOpenmeter_3(path, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MoometerProxyApi.proxyOpenmeter_3']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
         * @summary Proxy Openmeter
         * @param {string} path 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async proxyOpenmeter_4(path: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.proxyOpenmeter_4(path, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MoometerProxyApi.proxyOpenmeter_4']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MoometerProxyApi - factory interface
 * @export
 */
export const MoometerProxyApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MoometerProxyApiFp(configuration)
    return {
        /**
         * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
         * @summary Proxy Openmeter
         * @param {string} path 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        proxyOpenmeter(path: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.proxyOpenmeter(path, options).then((request) => request(axios, basePath));
        },
        /**
         * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
         * @summary Proxy Openmeter
         * @param {string} path 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        proxyOpenmeter_1(path: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.proxyOpenmeter_1(path, options).then((request) => request(axios, basePath));
        },
        /**
         * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
         * @summary Proxy Openmeter
         * @param {string} path 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        proxyOpenmeter_2(path: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.proxyOpenmeter_2(path, options).then((request) => request(axios, basePath));
        },
        /**
         * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
         * @summary Proxy Openmeter
         * @param {string} path 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        proxyOpenmeter_3(path: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.proxyOpenmeter_3(path, options).then((request) => request(axios, basePath));
        },
        /**
         * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
         * @summary Proxy Openmeter
         * @param {string} path 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        proxyOpenmeter_4(path: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.proxyOpenmeter_4(path, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MoometerProxyApi - interface
 * @export
 * @interface MoometerProxyApi
 */
export interface MoometerProxyApiInterface {
    /**
     * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
     * @summary Proxy Openmeter
     * @param {string} path 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoometerProxyApiInterface
     */
    proxyOpenmeter(path: string, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
     * @summary Proxy Openmeter
     * @param {string} path 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoometerProxyApiInterface
     */
    proxyOpenmeter_1(path: string, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
     * @summary Proxy Openmeter
     * @param {string} path 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoometerProxyApiInterface
     */
    proxyOpenmeter_2(path: string, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
     * @summary Proxy Openmeter
     * @param {string} path 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoometerProxyApiInterface
     */
    proxyOpenmeter_3(path: string, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
     * @summary Proxy Openmeter
     * @param {string} path 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoometerProxyApiInterface
     */
    proxyOpenmeter_4(path: string, options?: RawAxiosRequestConfig): AxiosPromise<any>;

}

/**
 * MoometerProxyApi - object-oriented interface
 * @export
 * @class MoometerProxyApi
 * @extends {BaseAPI}
 */
export class MoometerProxyApi extends BaseAPI implements MoometerProxyApiInterface {
    /**
     * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
     * @summary Proxy Openmeter
     * @param {string} path 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoometerProxyApi
     */
    public proxyOpenmeter(path: string, options?: RawAxiosRequestConfig) {
        return MoometerProxyApiFp(this.configuration).proxyOpenmeter(path, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
     * @summary Proxy Openmeter
     * @param {string} path 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoometerProxyApi
     */
    public proxyOpenmeter_1(path: string, options?: RawAxiosRequestConfig) {
        return MoometerProxyApiFp(this.configuration).proxyOpenmeter_1(path, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
     * @summary Proxy Openmeter
     * @param {string} path 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoometerProxyApi
     */
    public proxyOpenmeter_2(path: string, options?: RawAxiosRequestConfig) {
        return MoometerProxyApiFp(this.configuration).proxyOpenmeter_2(path, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
     * @summary Proxy Openmeter
     * @param {string} path 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoometerProxyApi
     */
    public proxyOpenmeter_3(path: string, options?: RawAxiosRequestConfig) {
        return MoometerProxyApiFp(this.configuration).proxyOpenmeter_3(path, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Generic pass-through proxy to Moo-meter with per-tenant OM-Namespace.
     * @summary Proxy Openmeter
     * @param {string} path 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoometerProxyApi
     */
    public proxyOpenmeter_4(path: string, options?: RawAxiosRequestConfig) {
        return MoometerProxyApiFp(this.configuration).proxyOpenmeter_4(path, options).then((request) => request(this.axios, this.basePath));
    }
}

