/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.1.0-rc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreatePortalTokenRequest } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { InvalidatePortalTokenRequest } from '../models';
/**
 * PortalApi - axios parameter creator
 * @export
 */
export const PortalApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create a portal token for a subject.  The token is scoped to the subject\'s tenant and pool (resolved server-side). Plaintext is returned only once — only the SHA-256 hash is stored. tenant_id is derived from server config (never a query param).
         * @summary Create Token Endpoint
         * @param {CreatePortalTokenRequest} createPortalTokenRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTokenEndpoint: async (createPortalTokenRequest: CreatePortalTokenRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createPortalTokenRequest' is not null or undefined
            assertParamExists('createTokenEndpoint', 'createPortalTokenRequest', createPortalTokenRequest)
            const localVarPath = `/v1/portal/tokens`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createPortalTokenRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Return resolved tenant/pool/subject for the authenticated portal token.  Called by MoolabsProvider on mount to resolve CLS queryParams (tenant_id, pool_id) without exposing them in browser code.
         * @summary Get Portal Context
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPortalContext: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/portal/context`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Invalidate portal token(s) by token value or subject.  At least one of token or subject must be provided. Revocation is soft — sets revoked_at, never deletes.
         * @summary Invalidate Tokens Endpoint
         * @param {InvalidatePortalTokenRequest} invalidatePortalTokenRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invalidateTokensEndpoint: async (invalidatePortalTokenRequest: InvalidatePortalTokenRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'invalidatePortalTokenRequest' is not null or undefined
            assertParamExists('invalidateTokensEndpoint', 'invalidatePortalTokenRequest', invalidatePortalTokenRequest)
            const localVarPath = `/v1/portal/tokens/invalidate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(invalidatePortalTokenRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List active portal tokens for tenant (optionally filtered by subject).
         * @summary List Tokens Endpoint
         * @param {string | null} [subject] Filter by subject
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTokensEndpoint: async (subject?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/portal/tokens`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (subject !== undefined) {
                localVarQueryParameter['subject'] = subject;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PortalApi - functional programming interface
 * @export
 */
export const PortalApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PortalApiAxiosParamCreator(configuration)
    return {
        /**
         * Create a portal token for a subject.  The token is scoped to the subject\'s tenant and pool (resolved server-side). Plaintext is returned only once — only the SHA-256 hash is stored. tenant_id is derived from server config (never a query param).
         * @summary Create Token Endpoint
         * @param {CreatePortalTokenRequest} createPortalTokenRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTokenEndpoint(createPortalTokenRequest: CreatePortalTokenRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTokenEndpoint(createPortalTokenRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PortalApi.createTokenEndpoint']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Return resolved tenant/pool/subject for the authenticated portal token.  Called by MoolabsProvider on mount to resolve CLS queryParams (tenant_id, pool_id) without exposing them in browser code.
         * @summary Get Portal Context
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPortalContext(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPortalContext(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PortalApi.getPortalContext']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Invalidate portal token(s) by token value or subject.  At least one of token or subject must be provided. Revocation is soft — sets revoked_at, never deletes.
         * @summary Invalidate Tokens Endpoint
         * @param {InvalidatePortalTokenRequest} invalidatePortalTokenRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async invalidateTokensEndpoint(invalidatePortalTokenRequest: InvalidatePortalTokenRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.invalidateTokensEndpoint(invalidatePortalTokenRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PortalApi.invalidateTokensEndpoint']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List active portal tokens for tenant (optionally filtered by subject).
         * @summary List Tokens Endpoint
         * @param {string | null} [subject] Filter by subject
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTokensEndpoint(subject?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTokensEndpoint(subject, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PortalApi.listTokensEndpoint']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PortalApi - factory interface
 * @export
 */
export const PortalApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PortalApiFp(configuration)
    return {
        /**
         * Create a portal token for a subject.  The token is scoped to the subject\'s tenant and pool (resolved server-side). Plaintext is returned only once — only the SHA-256 hash is stored. tenant_id is derived from server config (never a query param).
         * @summary Create Token Endpoint
         * @param {CreatePortalTokenRequest} createPortalTokenRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTokenEndpoint(createPortalTokenRequest: CreatePortalTokenRequest, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.createTokenEndpoint(createPortalTokenRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Return resolved tenant/pool/subject for the authenticated portal token.  Called by MoolabsProvider on mount to resolve CLS queryParams (tenant_id, pool_id) without exposing them in browser code.
         * @summary Get Portal Context
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPortalContext(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.getPortalContext(options).then((request) => request(axios, basePath));
        },
        /**
         * Invalidate portal token(s) by token value or subject.  At least one of token or subject must be provided. Revocation is soft — sets revoked_at, never deletes.
         * @summary Invalidate Tokens Endpoint
         * @param {InvalidatePortalTokenRequest} invalidatePortalTokenRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invalidateTokensEndpoint(invalidatePortalTokenRequest: InvalidatePortalTokenRequest, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.invalidateTokensEndpoint(invalidatePortalTokenRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * List active portal tokens for tenant (optionally filtered by subject).
         * @summary List Tokens Endpoint
         * @param {string | null} [subject] Filter by subject
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTokensEndpoint(subject?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.listTokensEndpoint(subject, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PortalApi - interface
 * @export
 * @interface PortalApi
 */
export interface PortalApiInterface {
    /**
     * Create a portal token for a subject.  The token is scoped to the subject\'s tenant and pool (resolved server-side). Plaintext is returned only once — only the SHA-256 hash is stored. tenant_id is derived from server config (never a query param).
     * @summary Create Token Endpoint
     * @param {CreatePortalTokenRequest} createPortalTokenRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PortalApiInterface
     */
    createTokenEndpoint(createPortalTokenRequest: CreatePortalTokenRequest, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * Return resolved tenant/pool/subject for the authenticated portal token.  Called by MoolabsProvider on mount to resolve CLS queryParams (tenant_id, pool_id) without exposing them in browser code.
     * @summary Get Portal Context
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PortalApiInterface
     */
    getPortalContext(options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * Invalidate portal token(s) by token value or subject.  At least one of token or subject must be provided. Revocation is soft — sets revoked_at, never deletes.
     * @summary Invalidate Tokens Endpoint
     * @param {InvalidatePortalTokenRequest} invalidatePortalTokenRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PortalApiInterface
     */
    invalidateTokensEndpoint(invalidatePortalTokenRequest: InvalidatePortalTokenRequest, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * List active portal tokens for tenant (optionally filtered by subject).
     * @summary List Tokens Endpoint
     * @param {string | null} [subject] Filter by subject
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PortalApiInterface
     */
    listTokensEndpoint(subject?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<any>;

}

/**
 * PortalApi - object-oriented interface
 * @export
 * @class PortalApi
 * @extends {BaseAPI}
 */
export class PortalApi extends BaseAPI implements PortalApiInterface {
    /**
     * Create a portal token for a subject.  The token is scoped to the subject\'s tenant and pool (resolved server-side). Plaintext is returned only once — only the SHA-256 hash is stored. tenant_id is derived from server config (never a query param).
     * @summary Create Token Endpoint
     * @param {CreatePortalTokenRequest} createPortalTokenRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PortalApi
     */
    public createTokenEndpoint(createPortalTokenRequest: CreatePortalTokenRequest, options?: RawAxiosRequestConfig) {
        return PortalApiFp(this.configuration).createTokenEndpoint(createPortalTokenRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Return resolved tenant/pool/subject for the authenticated portal token.  Called by MoolabsProvider on mount to resolve CLS queryParams (tenant_id, pool_id) without exposing them in browser code.
     * @summary Get Portal Context
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PortalApi
     */
    public getPortalContext(options?: RawAxiosRequestConfig) {
        return PortalApiFp(this.configuration).getPortalContext(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Invalidate portal token(s) by token value or subject.  At least one of token or subject must be provided. Revocation is soft — sets revoked_at, never deletes.
     * @summary Invalidate Tokens Endpoint
     * @param {InvalidatePortalTokenRequest} invalidatePortalTokenRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PortalApi
     */
    public invalidateTokensEndpoint(invalidatePortalTokenRequest: InvalidatePortalTokenRequest, options?: RawAxiosRequestConfig) {
        return PortalApiFp(this.configuration).invalidateTokensEndpoint(invalidatePortalTokenRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List active portal tokens for tenant (optionally filtered by subject).
     * @summary List Tokens Endpoint
     * @param {string | null} [subject] Filter by subject
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PortalApi
     */
    public listTokensEndpoint(subject?: string | null, options?: RawAxiosRequestConfig) {
        return PortalApiFp(this.configuration).listTokensEndpoint(subject, options).then((request) => request(this.axios, this.basePath));
    }
}

