/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ArcHTTPValidationError } from '../models';
// @ts-ignore
import type { PTPApprovalRequest } from '../models';
// @ts-ignore
import type { PTPCreateRequest } from '../models';
// @ts-ignore
import type { PTPFulfillRequest } from '../models';
// @ts-ignore
import type { PTPPaymentLinkResponse } from '../models';
/**
 * PromisesApi - axios parameter creator
 * @export
 */
export const PromisesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * POST /promises/{ptp_id}/approve — Approve an auto-proposed PTP: flip PROPOSED → OPEN, set ``case.next_promise_due_at``, complete the linked CONFIRM_PTP task.
         * @summary Approve Ptp Endpoint
         * @param {string} ptpId 
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {PTPApprovalRequest} [pTPApprovalRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approvePtpEndpoint: async (ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, pTPApprovalRequest?: PTPApprovalRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ptpId' is not null or undefined
            assertParamExists('approvePtpEndpoint', 'ptpId', ptpId)
            // verify required parameter 'xAPIKey' is not null or undefined
            assertParamExists('approvePtpEndpoint', 'xAPIKey', xAPIKey)
            const localVarPath = `/v1/arc/promises/{ptp_id}/approve`
                .replace(`{${"ptp_id"}}`, encodeURIComponent(String(ptpId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (xTenantId != null) {
                localVarHeaderParameter['X-Tenant-Id'] = String(xTenantId);
            }
            if (xOrgId != null) {
                localVarHeaderParameter['X-Org-Id'] = String(xOrgId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pTPApprovalRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * POST /promises-to-pay/{ptp_id}/break — Mark PTP as broken.
         * @summary Break Ptp Endpoint
         * @param {string} caseId 
         * @param {string} ptpId 
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        breakPtpEndpointV1Arc: async (caseId: string, ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'caseId' is not null or undefined
            assertParamExists('breakPtpEndpointV1Arc', 'caseId', caseId)
            // verify required parameter 'ptpId' is not null or undefined
            assertParamExists('breakPtpEndpointV1Arc', 'ptpId', ptpId)
            // verify required parameter 'xAPIKey' is not null or undefined
            assertParamExists('breakPtpEndpointV1Arc', 'xAPIKey', xAPIKey)
            const localVarPath = `/v1/arc/cases/{case_id}/promises-to-pay/{ptp_id}/break`
                .replace(`{${"case_id"}}`, encodeURIComponent(String(caseId)))
                .replace(`{${"ptp_id"}}`, encodeURIComponent(String(ptpId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (xTenantId != null) {
                localVarHeaderParameter['X-Tenant-Id'] = String(xTenantId);
            }
            if (xOrgId != null) {
                localVarHeaderParameter['X-Org-Id'] = String(xOrgId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * POST /promises-to-pay/{ptp_id}/cancel — Cancel PTP.
         * @summary Cancel Ptp Endpoint
         * @param {string} caseId 
         * @param {string} ptpId 
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelPtpEndpointV1Arc: async (caseId: string, ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'caseId' is not null or undefined
            assertParamExists('cancelPtpEndpointV1Arc', 'caseId', caseId)
            // verify required parameter 'ptpId' is not null or undefined
            assertParamExists('cancelPtpEndpointV1Arc', 'ptpId', ptpId)
            // verify required parameter 'xAPIKey' is not null or undefined
            assertParamExists('cancelPtpEndpointV1Arc', 'xAPIKey', xAPIKey)
            const localVarPath = `/v1/arc/cases/{case_id}/promises-to-pay/{ptp_id}/cancel`
                .replace(`{${"case_id"}}`, encodeURIComponent(String(caseId)))
                .replace(`{${"ptp_id"}}`, encodeURIComponent(String(ptpId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (xTenantId != null) {
                localVarHeaderParameter['X-Tenant-Id'] = String(xTenantId);
            }
            if (xOrgId != null) {
                localVarHeaderParameter['X-Org-Id'] = String(xOrgId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * POST /cases/{case_id}/promises-to-pay — Create a promise-to-pay.
         * @summary Create Ptp Endpoint
         * @param {string} caseId 
         * @param {string} xAPIKey 
         * @param {PTPCreateRequest} pTPCreateRequest 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPtpEndpointV1Arc: async (caseId: string, xAPIKey: string, pTPCreateRequest: PTPCreateRequest, xTenantId?: string, xOrgId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'caseId' is not null or undefined
            assertParamExists('createPtpEndpointV1Arc', 'caseId', caseId)
            // verify required parameter 'xAPIKey' is not null or undefined
            assertParamExists('createPtpEndpointV1Arc', 'xAPIKey', xAPIKey)
            // verify required parameter 'pTPCreateRequest' is not null or undefined
            assertParamExists('createPtpEndpointV1Arc', 'pTPCreateRequest', pTPCreateRequest)
            const localVarPath = `/v1/arc/cases/{case_id}/promises-to-pay`
                .replace(`{${"case_id"}}`, encodeURIComponent(String(caseId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (xTenantId != null) {
                localVarHeaderParameter['X-Tenant-Id'] = String(xTenantId);
            }
            if (xOrgId != null) {
                localVarHeaderParameter['X-Org-Id'] = String(xOrgId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pTPCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * POST /promises-to-pay/{ptp_id}/payment-link — Create a hosted card-payment link.
         * @summary Create Ptp Payment Link Endpoint
         * @param {string} caseId 
         * @param {string} ptpId 
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPtpPaymentLinkEndpointV1ArcCases: async (caseId: string, ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'caseId' is not null or undefined
            assertParamExists('createPtpPaymentLinkEndpointV1ArcCases', 'caseId', caseId)
            // verify required parameter 'ptpId' is not null or undefined
            assertParamExists('createPtpPaymentLinkEndpointV1ArcCases', 'ptpId', ptpId)
            // verify required parameter 'xAPIKey' is not null or undefined
            assertParamExists('createPtpPaymentLinkEndpointV1ArcCases', 'xAPIKey', xAPIKey)
            const localVarPath = `/v1/arc/cases/{case_id}/promises-to-pay/{ptp_id}/payment-link`
                .replace(`{${"case_id"}}`, encodeURIComponent(String(caseId)))
                .replace(`{${"ptp_id"}}`, encodeURIComponent(String(ptpId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (xTenantId != null) {
                localVarHeaderParameter['X-Tenant-Id'] = String(xTenantId);
            }
            if (xOrgId != null) {
                localVarHeaderParameter['X-Org-Id'] = String(xOrgId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * POST /promises-to-pay/{ptp_id}/fulfill — Record fulfillment.
         * @summary Fulfill Ptp Endpoint
         * @param {string} caseId 
         * @param {string} ptpId 
         * @param {string} xAPIKey 
         * @param {PTPFulfillRequest} pTPFulfillRequest 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fulfillPtpEndpointV1Arc: async (caseId: string, ptpId: string, xAPIKey: string, pTPFulfillRequest: PTPFulfillRequest, xTenantId?: string, xOrgId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'caseId' is not null or undefined
            assertParamExists('fulfillPtpEndpointV1Arc', 'caseId', caseId)
            // verify required parameter 'ptpId' is not null or undefined
            assertParamExists('fulfillPtpEndpointV1Arc', 'ptpId', ptpId)
            // verify required parameter 'xAPIKey' is not null or undefined
            assertParamExists('fulfillPtpEndpointV1Arc', 'xAPIKey', xAPIKey)
            // verify required parameter 'pTPFulfillRequest' is not null or undefined
            assertParamExists('fulfillPtpEndpointV1Arc', 'pTPFulfillRequest', pTPFulfillRequest)
            const localVarPath = `/v1/arc/cases/{case_id}/promises-to-pay/{ptp_id}/fulfill`
                .replace(`{${"case_id"}}`, encodeURIComponent(String(caseId)))
                .replace(`{${"ptp_id"}}`, encodeURIComponent(String(ptpId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (xTenantId != null) {
                localVarHeaderParameter['X-Tenant-Id'] = String(xTenantId);
            }
            if (xOrgId != null) {
                localVarHeaderParameter['X-Org-Id'] = String(xOrgId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pTPFulfillRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * GET /cases/{case_id}/promises-to-pay — List PTPs.
         * @summary List Ptps Endpoint
         * @param {string} caseId 
         * @param {string} xAPIKey 
         * @param {string} [status] 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPtpsEndpointV1Arc: async (caseId: string, xAPIKey: string, status?: string, xTenantId?: string, xOrgId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'caseId' is not null or undefined
            assertParamExists('listPtpsEndpointV1Arc', 'caseId', caseId)
            // verify required parameter 'xAPIKey' is not null or undefined
            assertParamExists('listPtpsEndpointV1Arc', 'xAPIKey', xAPIKey)
            const localVarPath = `/v1/arc/cases/{case_id}/promises-to-pay`
                .replace(`{${"case_id"}}`, encodeURIComponent(String(caseId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }


    
            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (xTenantId != null) {
                localVarHeaderParameter['X-Tenant-Id'] = String(xTenantId);
            }
            if (xOrgId != null) {
                localVarHeaderParameter['X-Org-Id'] = String(xOrgId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * POST /promises/{ptp_id}/reject — Reject an auto-proposed PTP: flip PROPOSED → CANCELLED, leave case scheduling untouched, complete the CONFIRM_PTP task with outcome=rejected.
         * @summary Reject Ptp Endpoint
         * @param {string} ptpId 
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {PTPApprovalRequest} [pTPApprovalRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rejectPtpEndpoint: async (ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, pTPApprovalRequest?: PTPApprovalRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ptpId' is not null or undefined
            assertParamExists('rejectPtpEndpoint', 'ptpId', ptpId)
            // verify required parameter 'xAPIKey' is not null or undefined
            assertParamExists('rejectPtpEndpoint', 'xAPIKey', xAPIKey)
            const localVarPath = `/v1/arc/promises/{ptp_id}/reject`
                .replace(`{${"ptp_id"}}`, encodeURIComponent(String(ptpId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xAPIKey != null) {
                localVarHeaderParameter['X-API-Key'] = String(xAPIKey);
            }
            if (xTenantId != null) {
                localVarHeaderParameter['X-Tenant-Id'] = String(xTenantId);
            }
            if (xOrgId != null) {
                localVarHeaderParameter['X-Org-Id'] = String(xOrgId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pTPApprovalRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PromisesApi - functional programming interface
 * @export
 */
export const PromisesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PromisesApiAxiosParamCreator(configuration)
    return {
        /**
         * POST /promises/{ptp_id}/approve — Approve an auto-proposed PTP: flip PROPOSED → OPEN, set ``case.next_promise_due_at``, complete the linked CONFIRM_PTP task.
         * @summary Approve Ptp Endpoint
         * @param {string} ptpId 
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {PTPApprovalRequest} [pTPApprovalRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async approvePtpEndpoint(ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, pTPApprovalRequest?: PTPApprovalRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.approvePtpEndpoint(ptpId, xAPIKey, xTenantId, xOrgId, pTPApprovalRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromisesApi.approvePtpEndpoint']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * POST /promises-to-pay/{ptp_id}/break — Mark PTP as broken.
         * @summary Break Ptp Endpoint
         * @param {string} caseId 
         * @param {string} ptpId 
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async breakPtpEndpointV1Arc(caseId: string, ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.breakPtpEndpointV1Arc(caseId, ptpId, xAPIKey, xTenantId, xOrgId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromisesApi.breakPtpEndpointV1Arc']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * POST /promises-to-pay/{ptp_id}/cancel — Cancel PTP.
         * @summary Cancel Ptp Endpoint
         * @param {string} caseId 
         * @param {string} ptpId 
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancelPtpEndpointV1Arc(caseId: string, ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancelPtpEndpointV1Arc(caseId, ptpId, xAPIKey, xTenantId, xOrgId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromisesApi.cancelPtpEndpointV1Arc']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * POST /cases/{case_id}/promises-to-pay — Create a promise-to-pay.
         * @summary Create Ptp Endpoint
         * @param {string} caseId 
         * @param {string} xAPIKey 
         * @param {PTPCreateRequest} pTPCreateRequest 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPtpEndpointV1Arc(caseId: string, xAPIKey: string, pTPCreateRequest: PTPCreateRequest, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPtpEndpointV1Arc(caseId, xAPIKey, pTPCreateRequest, xTenantId, xOrgId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromisesApi.createPtpEndpointV1Arc']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * POST /promises-to-pay/{ptp_id}/payment-link — Create a hosted card-payment link.
         * @summary Create Ptp Payment Link Endpoint
         * @param {string} caseId 
         * @param {string} ptpId 
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPtpPaymentLinkEndpointV1ArcCases(caseId: string, ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PTPPaymentLinkResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPtpPaymentLinkEndpointV1ArcCases(caseId, ptpId, xAPIKey, xTenantId, xOrgId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromisesApi.createPtpPaymentLinkEndpointV1ArcCases']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * POST /promises-to-pay/{ptp_id}/fulfill — Record fulfillment.
         * @summary Fulfill Ptp Endpoint
         * @param {string} caseId 
         * @param {string} ptpId 
         * @param {string} xAPIKey 
         * @param {PTPFulfillRequest} pTPFulfillRequest 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fulfillPtpEndpointV1Arc(caseId: string, ptpId: string, xAPIKey: string, pTPFulfillRequest: PTPFulfillRequest, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fulfillPtpEndpointV1Arc(caseId, ptpId, xAPIKey, pTPFulfillRequest, xTenantId, xOrgId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromisesApi.fulfillPtpEndpointV1Arc']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * GET /cases/{case_id}/promises-to-pay — List PTPs.
         * @summary List Ptps Endpoint
         * @param {string} caseId 
         * @param {string} xAPIKey 
         * @param {string} [status] 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPtpsEndpointV1Arc(caseId: string, xAPIKey: string, status?: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPtpsEndpointV1Arc(caseId, xAPIKey, status, xTenantId, xOrgId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromisesApi.listPtpsEndpointV1Arc']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * POST /promises/{ptp_id}/reject — Reject an auto-proposed PTP: flip PROPOSED → CANCELLED, leave case scheduling untouched, complete the CONFIRM_PTP task with outcome=rejected.
         * @summary Reject Ptp Endpoint
         * @param {string} ptpId 
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {PTPApprovalRequest} [pTPApprovalRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rejectPtpEndpoint(ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, pTPApprovalRequest?: PTPApprovalRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rejectPtpEndpoint(ptpId, xAPIKey, xTenantId, xOrgId, pTPApprovalRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromisesApi.rejectPtpEndpoint']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PromisesApi - factory interface
 * @export
 */
export const PromisesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PromisesApiFp(configuration)
    return {
        /**
         * POST /promises/{ptp_id}/approve — Approve an auto-proposed PTP: flip PROPOSED → OPEN, set ``case.next_promise_due_at``, complete the linked CONFIRM_PTP task.
         * @summary Approve Ptp Endpoint
         * @param {string} ptpId 
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {PTPApprovalRequest} [pTPApprovalRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approvePtpEndpoint(ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, pTPApprovalRequest?: PTPApprovalRequest, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.approvePtpEndpoint(ptpId, xAPIKey, xTenantId, xOrgId, pTPApprovalRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * POST /promises-to-pay/{ptp_id}/break — Mark PTP as broken.
         * @summary Break Ptp Endpoint
         * @param {string} caseId 
         * @param {string} ptpId 
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        breakPtpEndpointV1Arc(caseId: string, ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.breakPtpEndpointV1Arc(caseId, ptpId, xAPIKey, xTenantId, xOrgId, options).then((request) => request(axios, basePath));
        },
        /**
         * POST /promises-to-pay/{ptp_id}/cancel — Cancel PTP.
         * @summary Cancel Ptp Endpoint
         * @param {string} caseId 
         * @param {string} ptpId 
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelPtpEndpointV1Arc(caseId: string, ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.cancelPtpEndpointV1Arc(caseId, ptpId, xAPIKey, xTenantId, xOrgId, options).then((request) => request(axios, basePath));
        },
        /**
         * POST /cases/{case_id}/promises-to-pay — Create a promise-to-pay.
         * @summary Create Ptp Endpoint
         * @param {string} caseId 
         * @param {string} xAPIKey 
         * @param {PTPCreateRequest} pTPCreateRequest 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPtpEndpointV1Arc(caseId: string, xAPIKey: string, pTPCreateRequest: PTPCreateRequest, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.createPtpEndpointV1Arc(caseId, xAPIKey, pTPCreateRequest, xTenantId, xOrgId, options).then((request) => request(axios, basePath));
        },
        /**
         * POST /promises-to-pay/{ptp_id}/payment-link — Create a hosted card-payment link.
         * @summary Create Ptp Payment Link Endpoint
         * @param {string} caseId 
         * @param {string} ptpId 
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPtpPaymentLinkEndpointV1ArcCases(caseId: string, ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<PTPPaymentLinkResponse> {
            return localVarFp.createPtpPaymentLinkEndpointV1ArcCases(caseId, ptpId, xAPIKey, xTenantId, xOrgId, options).then((request) => request(axios, basePath));
        },
        /**
         * POST /promises-to-pay/{ptp_id}/fulfill — Record fulfillment.
         * @summary Fulfill Ptp Endpoint
         * @param {string} caseId 
         * @param {string} ptpId 
         * @param {string} xAPIKey 
         * @param {PTPFulfillRequest} pTPFulfillRequest 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fulfillPtpEndpointV1Arc(caseId: string, ptpId: string, xAPIKey: string, pTPFulfillRequest: PTPFulfillRequest, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.fulfillPtpEndpointV1Arc(caseId, ptpId, xAPIKey, pTPFulfillRequest, xTenantId, xOrgId, options).then((request) => request(axios, basePath));
        },
        /**
         * GET /cases/{case_id}/promises-to-pay — List PTPs.
         * @summary List Ptps Endpoint
         * @param {string} caseId 
         * @param {string} xAPIKey 
         * @param {string} [status] 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPtpsEndpointV1Arc(caseId: string, xAPIKey: string, status?: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.listPtpsEndpointV1Arc(caseId, xAPIKey, status, xTenantId, xOrgId, options).then((request) => request(axios, basePath));
        },
        /**
         * POST /promises/{ptp_id}/reject — Reject an auto-proposed PTP: flip PROPOSED → CANCELLED, leave case scheduling untouched, complete the CONFIRM_PTP task with outcome=rejected.
         * @summary Reject Ptp Endpoint
         * @param {string} ptpId 
         * @param {string} xAPIKey 
         * @param {string} [xTenantId] 
         * @param {string} [xOrgId] 
         * @param {PTPApprovalRequest} [pTPApprovalRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rejectPtpEndpoint(ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, pTPApprovalRequest?: PTPApprovalRequest, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.rejectPtpEndpoint(ptpId, xAPIKey, xTenantId, xOrgId, pTPApprovalRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PromisesApi - interface
 * @export
 * @interface PromisesApi
 */
export interface PromisesApiInterface {
    /**
     * POST /promises/{ptp_id}/approve — Approve an auto-proposed PTP: flip PROPOSED → OPEN, set ``case.next_promise_due_at``, complete the linked CONFIRM_PTP task.
     * @summary Approve Ptp Endpoint
     * @param {string} ptpId 
     * @param {string} xAPIKey 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {PTPApprovalRequest} [pTPApprovalRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromisesApiInterface
     */
    approvePtpEndpoint(ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, pTPApprovalRequest?: PTPApprovalRequest, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * POST /promises-to-pay/{ptp_id}/break — Mark PTP as broken.
     * @summary Break Ptp Endpoint
     * @param {string} caseId 
     * @param {string} ptpId 
     * @param {string} xAPIKey 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromisesApiInterface
     */
    breakPtpEndpointV1Arc(caseId: string, ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * POST /promises-to-pay/{ptp_id}/cancel — Cancel PTP.
     * @summary Cancel Ptp Endpoint
     * @param {string} caseId 
     * @param {string} ptpId 
     * @param {string} xAPIKey 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromisesApiInterface
     */
    cancelPtpEndpointV1Arc(caseId: string, ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * POST /cases/{case_id}/promises-to-pay — Create a promise-to-pay.
     * @summary Create Ptp Endpoint
     * @param {string} caseId 
     * @param {string} xAPIKey 
     * @param {PTPCreateRequest} pTPCreateRequest 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromisesApiInterface
     */
    createPtpEndpointV1Arc(caseId: string, xAPIKey: string, pTPCreateRequest: PTPCreateRequest, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * POST /promises-to-pay/{ptp_id}/payment-link — Create a hosted card-payment link.
     * @summary Create Ptp Payment Link Endpoint
     * @param {string} caseId 
     * @param {string} ptpId 
     * @param {string} xAPIKey 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromisesApiInterface
     */
    createPtpPaymentLinkEndpointV1ArcCases(caseId: string, ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<PTPPaymentLinkResponse>;

    /**
     * POST /promises-to-pay/{ptp_id}/fulfill — Record fulfillment.
     * @summary Fulfill Ptp Endpoint
     * @param {string} caseId 
     * @param {string} ptpId 
     * @param {string} xAPIKey 
     * @param {PTPFulfillRequest} pTPFulfillRequest 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromisesApiInterface
     */
    fulfillPtpEndpointV1Arc(caseId: string, ptpId: string, xAPIKey: string, pTPFulfillRequest: PTPFulfillRequest, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * GET /cases/{case_id}/promises-to-pay — List PTPs.
     * @summary List Ptps Endpoint
     * @param {string} caseId 
     * @param {string} xAPIKey 
     * @param {string} [status] 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromisesApiInterface
     */
    listPtpsEndpointV1Arc(caseId: string, xAPIKey: string, status?: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * POST /promises/{ptp_id}/reject — Reject an auto-proposed PTP: flip PROPOSED → CANCELLED, leave case scheduling untouched, complete the CONFIRM_PTP task with outcome=rejected.
     * @summary Reject Ptp Endpoint
     * @param {string} ptpId 
     * @param {string} xAPIKey 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {PTPApprovalRequest} [pTPApprovalRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromisesApiInterface
     */
    rejectPtpEndpoint(ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, pTPApprovalRequest?: PTPApprovalRequest, options?: RawAxiosRequestConfig): AxiosPromise<any>;

}

/**
 * PromisesApi - object-oriented interface
 * @export
 * @class PromisesApi
 * @extends {BaseAPI}
 */
export class PromisesApi extends BaseAPI implements PromisesApiInterface {
    /**
     * POST /promises/{ptp_id}/approve — Approve an auto-proposed PTP: flip PROPOSED → OPEN, set ``case.next_promise_due_at``, complete the linked CONFIRM_PTP task.
     * @summary Approve Ptp Endpoint
     * @param {string} ptpId 
     * @param {string} xAPIKey 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {PTPApprovalRequest} [pTPApprovalRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromisesApi
     */
    public approvePtpEndpoint(ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, pTPApprovalRequest?: PTPApprovalRequest, options?: RawAxiosRequestConfig) {
        return PromisesApiFp(this.configuration).approvePtpEndpoint(ptpId, xAPIKey, xTenantId, xOrgId, pTPApprovalRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * POST /promises-to-pay/{ptp_id}/break — Mark PTP as broken.
     * @summary Break Ptp Endpoint
     * @param {string} caseId 
     * @param {string} ptpId 
     * @param {string} xAPIKey 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromisesApi
     */
    public breakPtpEndpointV1Arc(caseId: string, ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig) {
        return PromisesApiFp(this.configuration).breakPtpEndpointV1Arc(caseId, ptpId, xAPIKey, xTenantId, xOrgId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * POST /promises-to-pay/{ptp_id}/cancel — Cancel PTP.
     * @summary Cancel Ptp Endpoint
     * @param {string} caseId 
     * @param {string} ptpId 
     * @param {string} xAPIKey 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromisesApi
     */
    public cancelPtpEndpointV1Arc(caseId: string, ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig) {
        return PromisesApiFp(this.configuration).cancelPtpEndpointV1Arc(caseId, ptpId, xAPIKey, xTenantId, xOrgId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * POST /cases/{case_id}/promises-to-pay — Create a promise-to-pay.
     * @summary Create Ptp Endpoint
     * @param {string} caseId 
     * @param {string} xAPIKey 
     * @param {PTPCreateRequest} pTPCreateRequest 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromisesApi
     */
    public createPtpEndpointV1Arc(caseId: string, xAPIKey: string, pTPCreateRequest: PTPCreateRequest, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig) {
        return PromisesApiFp(this.configuration).createPtpEndpointV1Arc(caseId, xAPIKey, pTPCreateRequest, xTenantId, xOrgId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * POST /promises-to-pay/{ptp_id}/payment-link — Create a hosted card-payment link.
     * @summary Create Ptp Payment Link Endpoint
     * @param {string} caseId 
     * @param {string} ptpId 
     * @param {string} xAPIKey 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromisesApi
     */
    public createPtpPaymentLinkEndpointV1ArcCases(caseId: string, ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig) {
        return PromisesApiFp(this.configuration).createPtpPaymentLinkEndpointV1ArcCases(caseId, ptpId, xAPIKey, xTenantId, xOrgId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * POST /promises-to-pay/{ptp_id}/fulfill — Record fulfillment.
     * @summary Fulfill Ptp Endpoint
     * @param {string} caseId 
     * @param {string} ptpId 
     * @param {string} xAPIKey 
     * @param {PTPFulfillRequest} pTPFulfillRequest 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromisesApi
     */
    public fulfillPtpEndpointV1Arc(caseId: string, ptpId: string, xAPIKey: string, pTPFulfillRequest: PTPFulfillRequest, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig) {
        return PromisesApiFp(this.configuration).fulfillPtpEndpointV1Arc(caseId, ptpId, xAPIKey, pTPFulfillRequest, xTenantId, xOrgId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * GET /cases/{case_id}/promises-to-pay — List PTPs.
     * @summary List Ptps Endpoint
     * @param {string} caseId 
     * @param {string} xAPIKey 
     * @param {string} [status] 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromisesApi
     */
    public listPtpsEndpointV1Arc(caseId: string, xAPIKey: string, status?: string, xTenantId?: string, xOrgId?: string, options?: RawAxiosRequestConfig) {
        return PromisesApiFp(this.configuration).listPtpsEndpointV1Arc(caseId, xAPIKey, status, xTenantId, xOrgId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * POST /promises/{ptp_id}/reject — Reject an auto-proposed PTP: flip PROPOSED → CANCELLED, leave case scheduling untouched, complete the CONFIRM_PTP task with outcome=rejected.
     * @summary Reject Ptp Endpoint
     * @param {string} ptpId 
     * @param {string} xAPIKey 
     * @param {string} [xTenantId] 
     * @param {string} [xOrgId] 
     * @param {PTPApprovalRequest} [pTPApprovalRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PromisesApi
     */
    public rejectPtpEndpoint(ptpId: string, xAPIKey: string, xTenantId?: string, xOrgId?: string, pTPApprovalRequest?: PTPApprovalRequest, options?: RawAxiosRequestConfig) {
        return PromisesApiFp(this.configuration).rejectPtpEndpoint(ptpId, xAPIKey, xTenantId, xOrgId, pTPApprovalRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

