/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AcuteHTTPValidationError } from '../models';
// @ts-ignore
import type { SDKBatchIngestRequest } from '../models';
// @ts-ignore
import type { SDKBatchIngestResponse } from '../models';
/**
 * SdkIngestApi - axios parameter creator
 * @export
 */
export const SdkIngestApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Ingest Sdk Batch
         * @param {SDKBatchIngestRequest} sDKBatchIngestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingestSdkSpans: async (sDKBatchIngestRequest: SDKBatchIngestRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sDKBatchIngestRequest' is not null or undefined
            assertParamExists('ingestSdkSpans', 'sDKBatchIngestRequest', sDKBatchIngestRequest)
            const localVarPath = `/api/v1/ingest/batch`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication APIKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sDKBatchIngestRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SdkIngestApi - functional programming interface
 * @export
 */
export const SdkIngestApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SdkIngestApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Ingest Sdk Batch
         * @param {SDKBatchIngestRequest} sDKBatchIngestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ingestSdkSpans(sDKBatchIngestRequest: SDKBatchIngestRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SDKBatchIngestResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ingestSdkSpans(sDKBatchIngestRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SdkIngestApi.ingestSdkSpans']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SdkIngestApi - factory interface
 * @export
 */
export const SdkIngestApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SdkIngestApiFp(configuration)
    return {
        /**
         * 
         * @summary Ingest Sdk Batch
         * @param {SDKBatchIngestRequest} sDKBatchIngestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingestSdkSpans(sDKBatchIngestRequest: SDKBatchIngestRequest, options?: RawAxiosRequestConfig): AxiosPromise<SDKBatchIngestResponse> {
            return localVarFp.ingestSdkSpans(sDKBatchIngestRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SdkIngestApi - interface
 * @export
 * @interface SdkIngestApi
 */
export interface SdkIngestApiInterface {
    /**
     * 
     * @summary Ingest Sdk Batch
     * @param {SDKBatchIngestRequest} sDKBatchIngestRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SdkIngestApiInterface
     */
    ingestSdkSpans(sDKBatchIngestRequest: SDKBatchIngestRequest, options?: RawAxiosRequestConfig): AxiosPromise<SDKBatchIngestResponse>;

}

/**
 * SdkIngestApi - object-oriented interface
 * @export
 * @class SdkIngestApi
 * @extends {BaseAPI}
 */
export class SdkIngestApi extends BaseAPI implements SdkIngestApiInterface {
    /**
     * 
     * @summary Ingest Sdk Batch
     * @param {SDKBatchIngestRequest} sDKBatchIngestRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SdkIngestApi
     */
    public ingestSdkSpans(sDKBatchIngestRequest: SDKBatchIngestRequest, options?: RawAxiosRequestConfig) {
        return SdkIngestApiFp(this.configuration).ingestSdkSpans(sDKBatchIngestRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

