/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.0.0-rc5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CancelSubscriptionRequest } from '../models';
// @ts-ignore
import type { CustomerSubscriptionOrderBy } from '../models';
// @ts-ignore
import type { MigrateSubscriptionRequest } from '../models';
// @ts-ignore
import type { SortOrder } from '../models';
// @ts-ignore
import type { Subscription } from '../models';
// @ts-ignore
import type { SubscriptionAddon } from '../models';
// @ts-ignore
import type { SubscriptionAddonCreate } from '../models';
// @ts-ignore
import type { SubscriptionAddonUpdate } from '../models';
// @ts-ignore
import type { SubscriptionBadRequestErrorResponse } from '../models';
// @ts-ignore
import type { SubscriptionChange } from '../models';
// @ts-ignore
import type { SubscriptionChangeResponseBody } from '../models';
// @ts-ignore
import type { SubscriptionConflictErrorResponse } from '../models';
// @ts-ignore
import type { SubscriptionCreate } from '../models';
// @ts-ignore
import type { SubscriptionEdit } from '../models';
// @ts-ignore
import type { SubscriptionExpanded } from '../models';
// @ts-ignore
import type { SubscriptionPaginatedResponse } from '../models';
// @ts-ignore
import type { SubscriptionStatus } from '../models';
// @ts-ignore
import type { UnexpectedProblemResponse } from '../models';
/**
 * SubscriptionsApi - axios parameter creator
 * @export
 */
export const SubscriptionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Cancels the subscription. Will result in a scheduling conflict if there are other subscriptions scheduled to start after the cancellation time.
         * @summary Cancel subscription
         * @param {string} subscriptionId 
         * @param {CancelSubscriptionRequest} cancelSubscriptionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelSubscription: async (subscriptionId: string, cancelSubscriptionRequest: CancelSubscriptionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subscriptionId' is not null or undefined
            assertParamExists('cancelSubscription', 'subscriptionId', subscriptionId)
            // verify required parameter 'cancelSubscriptionRequest' is not null or undefined
            assertParamExists('cancelSubscription', 'cancelSubscriptionRequest', cancelSubscriptionRequest)
            const localVarPath = `/api/v1/subscriptions/{subscriptionId}/cancel`
                .replace(`{${"subscriptionId"}}`, encodeURIComponent(String(subscriptionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cancelSubscriptionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Closes a running subscription and starts a new one according to the specification. Can be used for upgrades, downgrades, and plan changes.
         * @summary Change subscription
         * @param {string} subscriptionId 
         * @param {SubscriptionChange} subscriptionChange 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changeSubscription: async (subscriptionId: string, subscriptionChange: SubscriptionChange, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subscriptionId' is not null or undefined
            assertParamExists('changeSubscription', 'subscriptionId', subscriptionId)
            // verify required parameter 'subscriptionChange' is not null or undefined
            assertParamExists('changeSubscription', 'subscriptionChange', subscriptionChange)
            const localVarPath = `/api/v1/subscriptions/{subscriptionId}/change`
                .replace(`{${"subscriptionId"}}`, encodeURIComponent(String(subscriptionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(subscriptionChange, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create subscription
         * @param {SubscriptionCreate} subscriptionCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSubscription: async (subscriptionCreate: SubscriptionCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subscriptionCreate' is not null or undefined
            assertParamExists('createSubscription', 'subscriptionCreate', subscriptionCreate)
            const localVarPath = `/api/v1/subscriptions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(subscriptionCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new subscription addon, either providing the key or the id of the addon.
         * @summary Create subscription addon
         * @param {string} subscriptionId 
         * @param {SubscriptionAddonCreate} subscriptionAddonCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSubscriptionAddon: async (subscriptionId: string, subscriptionAddonCreate: SubscriptionAddonCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subscriptionId' is not null or undefined
            assertParamExists('createSubscriptionAddon', 'subscriptionId', subscriptionId)
            // verify required parameter 'subscriptionAddonCreate' is not null or undefined
            assertParamExists('createSubscriptionAddon', 'subscriptionAddonCreate', subscriptionAddonCreate)
            const localVarPath = `/api/v1/subscriptions/{subscriptionId}/addons`
                .replace(`{${"subscriptionId"}}`, encodeURIComponent(String(subscriptionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(subscriptionAddonCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Deletes a subscription. Only scheduled subscriptions can be deleted.
         * @summary Delete subscription
         * @param {string} subscriptionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSubscription: async (subscriptionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subscriptionId' is not null or undefined
            assertParamExists('deleteSubscription', 'subscriptionId', subscriptionId)
            const localVarPath = `/api/v1/subscriptions/{subscriptionId}`
                .replace(`{${"subscriptionId"}}`, encodeURIComponent(String(subscriptionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Batch processing commands for manipulating running subscriptions. The key format is `/phases/{phaseKey}` or `/phases/{phaseKey}/items/{itemKey}`.
         * @summary Edit subscription
         * @param {string} subscriptionId 
         * @param {SubscriptionEdit} subscriptionEdit 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editSubscription: async (subscriptionId: string, subscriptionEdit: SubscriptionEdit, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subscriptionId' is not null or undefined
            assertParamExists('editSubscription', 'subscriptionId', subscriptionId)
            // verify required parameter 'subscriptionEdit' is not null or undefined
            assertParamExists('editSubscription', 'subscriptionEdit', subscriptionEdit)
            const localVarPath = `/api/v1/subscriptions/{subscriptionId}`
                .replace(`{${"subscriptionId"}}`, encodeURIComponent(String(subscriptionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(subscriptionEdit, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a subscription addon by id.
         * @summary Get subscription addon
         * @param {string} subscriptionId 
         * @param {string} subscriptionAddonId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubscriptionAddon: async (subscriptionId: string, subscriptionAddonId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subscriptionId' is not null or undefined
            assertParamExists('getSubscriptionAddon', 'subscriptionId', subscriptionId)
            // verify required parameter 'subscriptionAddonId' is not null or undefined
            assertParamExists('getSubscriptionAddon', 'subscriptionAddonId', subscriptionAddonId)
            const localVarPath = `/api/v1/subscriptions/{subscriptionId}/addons/{subscriptionAddonId}`
                .replace(`{${"subscriptionId"}}`, encodeURIComponent(String(subscriptionId)))
                .replace(`{${"subscriptionAddonId"}}`, encodeURIComponent(String(subscriptionAddonId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get subscription
         * @param {string} subscriptionId 
         * @param {string} [at] The time at which the subscription should be queried. If not provided the current time is used.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubscriptionGet: async (subscriptionId: string, at?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subscriptionId' is not null or undefined
            assertParamExists('getSubscriptionGet', 'subscriptionId', subscriptionId)
            const localVarPath = `/api/v1/subscriptions/{subscriptionId}`
                .replace(`{${"subscriptionId"}}`, encodeURIComponent(String(subscriptionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (at !== undefined) {
                localVarQueryParameter['at'] = (at as any instanceof Date) ?
                    (at as any).toISOString() :
                    at;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List all addons of a subscription. In the returned list will match to a set unique by addonId.
         * @summary List subscription addons
         * @param {string} subscriptionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSubscriptionAddons: async (subscriptionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subscriptionId' is not null or undefined
            assertParamExists('listSubscriptionAddons', 'subscriptionId', subscriptionId)
            const localVarPath = `/api/v1/subscriptions/{subscriptionId}/addons`
                .replace(`{${"subscriptionId"}}`, encodeURIComponent(String(subscriptionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Lists all subscriptions for the current namespace. Optionally filter by customer or status.
         * @summary List subscriptions
         * @param {string} [customerId] Filter by customer ID.
         * @param {Array<SubscriptionStatus>} [status] 
         * @param {SortOrder} [order] The order direction.
         * @param {CustomerSubscriptionOrderBy} [orderBy] The order by field.
         * @param {number} [page] Page index.  Default is 1.
         * @param {number} [pageSize] The maximum number of items per page.  Default is 100.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSubscriptions: async (customerId?: string, status?: Array<SubscriptionStatus>, order?: SortOrder, orderBy?: CustomerSubscriptionOrderBy, page?: number, pageSize?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/subscriptions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (customerId !== undefined) {
                localVarQueryParameter['customerId'] = customerId;
            }

            if (status) {
                localVarQueryParameter['status'] = status;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['orderBy'] = orderBy;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Migrates the subscripiton to the provided version of the current plan. If possible, the migration will be done immediately. If not, the migration will be scheduled to the end of the current billing period.
         * @summary Migrate subscription
         * @param {string} subscriptionId 
         * @param {MigrateSubscriptionRequest} migrateSubscriptionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        migrateSubscription: async (subscriptionId: string, migrateSubscriptionRequest: MigrateSubscriptionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subscriptionId' is not null or undefined
            assertParamExists('migrateSubscription', 'subscriptionId', subscriptionId)
            // verify required parameter 'migrateSubscriptionRequest' is not null or undefined
            assertParamExists('migrateSubscription', 'migrateSubscriptionRequest', migrateSubscriptionRequest)
            const localVarPath = `/api/v1/subscriptions/{subscriptionId}/migrate`
                .replace(`{${"subscriptionId"}}`, encodeURIComponent(String(subscriptionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(migrateSubscriptionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Restores a canceled subscription. Any subscription scheduled to start later will be deleted and this subscription will be continued indefinitely.
         * @summary Restore subscription
         * @param {string} subscriptionId 
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        restoreSubscription: async (subscriptionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subscriptionId' is not null or undefined
            assertParamExists('restoreSubscription', 'subscriptionId', subscriptionId)
            const localVarPath = `/api/v1/subscriptions/{subscriptionId}/restore`
                .replace(`{${"subscriptionId"}}`, encodeURIComponent(String(subscriptionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Cancels the scheduled cancelation.
         * @summary Unschedule cancelation
         * @param {string} subscriptionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unscheduleCancelation: async (subscriptionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subscriptionId' is not null or undefined
            assertParamExists('unscheduleCancelation', 'subscriptionId', subscriptionId)
            const localVarPath = `/api/v1/subscriptions/{subscriptionId}/unschedule-cancelation`
                .replace(`{${"subscriptionId"}}`, encodeURIComponent(String(subscriptionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates a subscription addon (allows changing the quantity: purchasing more instances or cancelling the current instances)
         * @summary Update subscription addon
         * @param {string} subscriptionId 
         * @param {string} subscriptionAddonId 
         * @param {SubscriptionAddonUpdate} subscriptionAddonUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSubscriptionAddon: async (subscriptionId: string, subscriptionAddonId: string, subscriptionAddonUpdate: SubscriptionAddonUpdate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subscriptionId' is not null or undefined
            assertParamExists('updateSubscriptionAddon', 'subscriptionId', subscriptionId)
            // verify required parameter 'subscriptionAddonId' is not null or undefined
            assertParamExists('updateSubscriptionAddon', 'subscriptionAddonId', subscriptionAddonId)
            // verify required parameter 'subscriptionAddonUpdate' is not null or undefined
            assertParamExists('updateSubscriptionAddon', 'subscriptionAddonUpdate', subscriptionAddonUpdate)
            const localVarPath = `/api/v1/subscriptions/{subscriptionId}/addons/{subscriptionAddonId}`
                .replace(`{${"subscriptionId"}}`, encodeURIComponent(String(subscriptionId)))
                .replace(`{${"subscriptionAddonId"}}`, encodeURIComponent(String(subscriptionAddonId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(subscriptionAddonUpdate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SubscriptionsApi - functional programming interface
 * @export
 */
export const SubscriptionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SubscriptionsApiAxiosParamCreator(configuration)
    return {
        /**
         * Cancels the subscription. Will result in a scheduling conflict if there are other subscriptions scheduled to start after the cancellation time.
         * @summary Cancel subscription
         * @param {string} subscriptionId 
         * @param {CancelSubscriptionRequest} cancelSubscriptionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancelSubscription(subscriptionId: string, cancelSubscriptionRequest: CancelSubscriptionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Subscription>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancelSubscription(subscriptionId, cancelSubscriptionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.cancelSubscription']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Closes a running subscription and starts a new one according to the specification. Can be used for upgrades, downgrades, and plan changes.
         * @summary Change subscription
         * @param {string} subscriptionId 
         * @param {SubscriptionChange} subscriptionChange 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async changeSubscription(subscriptionId: string, subscriptionChange: SubscriptionChange, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubscriptionChangeResponseBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.changeSubscription(subscriptionId, subscriptionChange, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.changeSubscription']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create subscription
         * @param {SubscriptionCreate} subscriptionCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSubscription(subscriptionCreate: SubscriptionCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Subscription>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSubscription(subscriptionCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.createSubscription']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a new subscription addon, either providing the key or the id of the addon.
         * @summary Create subscription addon
         * @param {string} subscriptionId 
         * @param {SubscriptionAddonCreate} subscriptionAddonCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSubscriptionAddon(subscriptionId: string, subscriptionAddonCreate: SubscriptionAddonCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubscriptionAddon>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSubscriptionAddon(subscriptionId, subscriptionAddonCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.createSubscriptionAddon']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Deletes a subscription. Only scheduled subscriptions can be deleted.
         * @summary Delete subscription
         * @param {string} subscriptionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSubscription(subscriptionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSubscription(subscriptionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.deleteSubscription']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Batch processing commands for manipulating running subscriptions. The key format is `/phases/{phaseKey}` or `/phases/{phaseKey}/items/{itemKey}`.
         * @summary Edit subscription
         * @param {string} subscriptionId 
         * @param {SubscriptionEdit} subscriptionEdit 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async editSubscription(subscriptionId: string, subscriptionEdit: SubscriptionEdit, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Subscription>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.editSubscription(subscriptionId, subscriptionEdit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.editSubscription']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get a subscription addon by id.
         * @summary Get subscription addon
         * @param {string} subscriptionId 
         * @param {string} subscriptionAddonId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSubscriptionAddon(subscriptionId: string, subscriptionAddonId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubscriptionAddon>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSubscriptionAddon(subscriptionId, subscriptionAddonId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.getSubscriptionAddon']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get subscription
         * @param {string} subscriptionId 
         * @param {string} [at] The time at which the subscription should be queried. If not provided the current time is used.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSubscriptionGet(subscriptionId: string, at?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubscriptionExpanded>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSubscriptionGet(subscriptionId, at, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.getSubscriptionGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List all addons of a subscription. In the returned list will match to a set unique by addonId.
         * @summary List subscription addons
         * @param {string} subscriptionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSubscriptionAddons(subscriptionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SubscriptionAddon>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSubscriptionAddons(subscriptionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.listSubscriptionAddons']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Lists all subscriptions for the current namespace. Optionally filter by customer or status.
         * @summary List subscriptions
         * @param {string} [customerId] Filter by customer ID.
         * @param {Array<SubscriptionStatus>} [status] 
         * @param {SortOrder} [order] The order direction.
         * @param {CustomerSubscriptionOrderBy} [orderBy] The order by field.
         * @param {number} [page] Page index.  Default is 1.
         * @param {number} [pageSize] The maximum number of items per page.  Default is 100.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSubscriptions(customerId?: string, status?: Array<SubscriptionStatus>, order?: SortOrder, orderBy?: CustomerSubscriptionOrderBy, page?: number, pageSize?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubscriptionPaginatedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSubscriptions(customerId, status, order, orderBy, page, pageSize, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.listSubscriptions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Migrates the subscripiton to the provided version of the current plan. If possible, the migration will be done immediately. If not, the migration will be scheduled to the end of the current billing period.
         * @summary Migrate subscription
         * @param {string} subscriptionId 
         * @param {MigrateSubscriptionRequest} migrateSubscriptionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async migrateSubscription(subscriptionId: string, migrateSubscriptionRequest: MigrateSubscriptionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubscriptionChangeResponseBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.migrateSubscription(subscriptionId, migrateSubscriptionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.migrateSubscription']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Restores a canceled subscription. Any subscription scheduled to start later will be deleted and this subscription will be continued indefinitely.
         * @summary Restore subscription
         * @param {string} subscriptionId 
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        async restoreSubscription(subscriptionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Subscription>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.restoreSubscription(subscriptionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.restoreSubscription']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Cancels the scheduled cancelation.
         * @summary Unschedule cancelation
         * @param {string} subscriptionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async unscheduleCancelation(subscriptionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Subscription>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.unscheduleCancelation(subscriptionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.unscheduleCancelation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Updates a subscription addon (allows changing the quantity: purchasing more instances or cancelling the current instances)
         * @summary Update subscription addon
         * @param {string} subscriptionId 
         * @param {string} subscriptionAddonId 
         * @param {SubscriptionAddonUpdate} subscriptionAddonUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSubscriptionAddon(subscriptionId: string, subscriptionAddonId: string, subscriptionAddonUpdate: SubscriptionAddonUpdate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubscriptionAddon>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSubscriptionAddon(subscriptionId, subscriptionAddonId, subscriptionAddonUpdate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.updateSubscriptionAddon']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SubscriptionsApi - factory interface
 * @export
 */
export const SubscriptionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SubscriptionsApiFp(configuration)
    return {
        /**
         * Cancels the subscription. Will result in a scheduling conflict if there are other subscriptions scheduled to start after the cancellation time.
         * @summary Cancel subscription
         * @param {string} subscriptionId 
         * @param {CancelSubscriptionRequest} cancelSubscriptionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelSubscription(subscriptionId: string, cancelSubscriptionRequest: CancelSubscriptionRequest, options?: RawAxiosRequestConfig): AxiosPromise<Subscription> {
            return localVarFp.cancelSubscription(subscriptionId, cancelSubscriptionRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Closes a running subscription and starts a new one according to the specification. Can be used for upgrades, downgrades, and plan changes.
         * @summary Change subscription
         * @param {string} subscriptionId 
         * @param {SubscriptionChange} subscriptionChange 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changeSubscription(subscriptionId: string, subscriptionChange: SubscriptionChange, options?: RawAxiosRequestConfig): AxiosPromise<SubscriptionChangeResponseBody> {
            return localVarFp.changeSubscription(subscriptionId, subscriptionChange, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create subscription
         * @param {SubscriptionCreate} subscriptionCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSubscription(subscriptionCreate: SubscriptionCreate, options?: RawAxiosRequestConfig): AxiosPromise<Subscription> {
            return localVarFp.createSubscription(subscriptionCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new subscription addon, either providing the key or the id of the addon.
         * @summary Create subscription addon
         * @param {string} subscriptionId 
         * @param {SubscriptionAddonCreate} subscriptionAddonCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSubscriptionAddon(subscriptionId: string, subscriptionAddonCreate: SubscriptionAddonCreate, options?: RawAxiosRequestConfig): AxiosPromise<SubscriptionAddon> {
            return localVarFp.createSubscriptionAddon(subscriptionId, subscriptionAddonCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * Deletes a subscription. Only scheduled subscriptions can be deleted.
         * @summary Delete subscription
         * @param {string} subscriptionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSubscription(subscriptionId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteSubscription(subscriptionId, options).then((request) => request(axios, basePath));
        },
        /**
         * Batch processing commands for manipulating running subscriptions. The key format is `/phases/{phaseKey}` or `/phases/{phaseKey}/items/{itemKey}`.
         * @summary Edit subscription
         * @param {string} subscriptionId 
         * @param {SubscriptionEdit} subscriptionEdit 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editSubscription(subscriptionId: string, subscriptionEdit: SubscriptionEdit, options?: RawAxiosRequestConfig): AxiosPromise<Subscription> {
            return localVarFp.editSubscription(subscriptionId, subscriptionEdit, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a subscription addon by id.
         * @summary Get subscription addon
         * @param {string} subscriptionId 
         * @param {string} subscriptionAddonId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubscriptionAddon(subscriptionId: string, subscriptionAddonId: string, options?: RawAxiosRequestConfig): AxiosPromise<SubscriptionAddon> {
            return localVarFp.getSubscriptionAddon(subscriptionId, subscriptionAddonId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get subscription
         * @param {string} subscriptionId 
         * @param {string} [at] The time at which the subscription should be queried. If not provided the current time is used.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubscriptionGet(subscriptionId: string, at?: string, options?: RawAxiosRequestConfig): AxiosPromise<SubscriptionExpanded> {
            return localVarFp.getSubscriptionGet(subscriptionId, at, options).then((request) => request(axios, basePath));
        },
        /**
         * List all addons of a subscription. In the returned list will match to a set unique by addonId.
         * @summary List subscription addons
         * @param {string} subscriptionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSubscriptionAddons(subscriptionId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<SubscriptionAddon>> {
            return localVarFp.listSubscriptionAddons(subscriptionId, options).then((request) => request(axios, basePath));
        },
        /**
         * Lists all subscriptions for the current namespace. Optionally filter by customer or status.
         * @summary List subscriptions
         * @param {string} [customerId] Filter by customer ID.
         * @param {Array<SubscriptionStatus>} [status] 
         * @param {SortOrder} [order] The order direction.
         * @param {CustomerSubscriptionOrderBy} [orderBy] The order by field.
         * @param {number} [page] Page index.  Default is 1.
         * @param {number} [pageSize] The maximum number of items per page.  Default is 100.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSubscriptions(customerId?: string, status?: Array<SubscriptionStatus>, order?: SortOrder, orderBy?: CustomerSubscriptionOrderBy, page?: number, pageSize?: number, options?: RawAxiosRequestConfig): AxiosPromise<SubscriptionPaginatedResponse> {
            return localVarFp.listSubscriptions(customerId, status, order, orderBy, page, pageSize, options).then((request) => request(axios, basePath));
        },
        /**
         * Migrates the subscripiton to the provided version of the current plan. If possible, the migration will be done immediately. If not, the migration will be scheduled to the end of the current billing period.
         * @summary Migrate subscription
         * @param {string} subscriptionId 
         * @param {MigrateSubscriptionRequest} migrateSubscriptionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        migrateSubscription(subscriptionId: string, migrateSubscriptionRequest: MigrateSubscriptionRequest, options?: RawAxiosRequestConfig): AxiosPromise<SubscriptionChangeResponseBody> {
            return localVarFp.migrateSubscription(subscriptionId, migrateSubscriptionRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Restores a canceled subscription. Any subscription scheduled to start later will be deleted and this subscription will be continued indefinitely.
         * @summary Restore subscription
         * @param {string} subscriptionId 
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        restoreSubscription(subscriptionId: string, options?: RawAxiosRequestConfig): AxiosPromise<Subscription> {
            return localVarFp.restoreSubscription(subscriptionId, options).then((request) => request(axios, basePath));
        },
        /**
         * Cancels the scheduled cancelation.
         * @summary Unschedule cancelation
         * @param {string} subscriptionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unscheduleCancelation(subscriptionId: string, options?: RawAxiosRequestConfig): AxiosPromise<Subscription> {
            return localVarFp.unscheduleCancelation(subscriptionId, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates a subscription addon (allows changing the quantity: purchasing more instances or cancelling the current instances)
         * @summary Update subscription addon
         * @param {string} subscriptionId 
         * @param {string} subscriptionAddonId 
         * @param {SubscriptionAddonUpdate} subscriptionAddonUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSubscriptionAddon(subscriptionId: string, subscriptionAddonId: string, subscriptionAddonUpdate: SubscriptionAddonUpdate, options?: RawAxiosRequestConfig): AxiosPromise<SubscriptionAddon> {
            return localVarFp.updateSubscriptionAddon(subscriptionId, subscriptionAddonId, subscriptionAddonUpdate, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SubscriptionsApi - interface
 * @export
 * @interface SubscriptionsApi
 */
export interface SubscriptionsApiInterface {
    /**
     * Cancels the subscription. Will result in a scheduling conflict if there are other subscriptions scheduled to start after the cancellation time.
     * @summary Cancel subscription
     * @param {string} subscriptionId 
     * @param {CancelSubscriptionRequest} cancelSubscriptionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApiInterface
     */
    cancelSubscription(subscriptionId: string, cancelSubscriptionRequest: CancelSubscriptionRequest, options?: RawAxiosRequestConfig): AxiosPromise<Subscription>;

    /**
     * Closes a running subscription and starts a new one according to the specification. Can be used for upgrades, downgrades, and plan changes.
     * @summary Change subscription
     * @param {string} subscriptionId 
     * @param {SubscriptionChange} subscriptionChange 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApiInterface
     */
    changeSubscription(subscriptionId: string, subscriptionChange: SubscriptionChange, options?: RawAxiosRequestConfig): AxiosPromise<SubscriptionChangeResponseBody>;

    /**
     * 
     * @summary Create subscription
     * @param {SubscriptionCreate} subscriptionCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApiInterface
     */
    createSubscription(subscriptionCreate: SubscriptionCreate, options?: RawAxiosRequestConfig): AxiosPromise<Subscription>;

    /**
     * Create a new subscription addon, either providing the key or the id of the addon.
     * @summary Create subscription addon
     * @param {string} subscriptionId 
     * @param {SubscriptionAddonCreate} subscriptionAddonCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApiInterface
     */
    createSubscriptionAddon(subscriptionId: string, subscriptionAddonCreate: SubscriptionAddonCreate, options?: RawAxiosRequestConfig): AxiosPromise<SubscriptionAddon>;

    /**
     * Deletes a subscription. Only scheduled subscriptions can be deleted.
     * @summary Delete subscription
     * @param {string} subscriptionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApiInterface
     */
    deleteSubscription(subscriptionId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Batch processing commands for manipulating running subscriptions. The key format is `/phases/{phaseKey}` or `/phases/{phaseKey}/items/{itemKey}`.
     * @summary Edit subscription
     * @param {string} subscriptionId 
     * @param {SubscriptionEdit} subscriptionEdit 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApiInterface
     */
    editSubscription(subscriptionId: string, subscriptionEdit: SubscriptionEdit, options?: RawAxiosRequestConfig): AxiosPromise<Subscription>;

    /**
     * Get a subscription addon by id.
     * @summary Get subscription addon
     * @param {string} subscriptionId 
     * @param {string} subscriptionAddonId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApiInterface
     */
    getSubscriptionAddon(subscriptionId: string, subscriptionAddonId: string, options?: RawAxiosRequestConfig): AxiosPromise<SubscriptionAddon>;

    /**
     * 
     * @summary Get subscription
     * @param {string} subscriptionId 
     * @param {string} [at] The time at which the subscription should be queried. If not provided the current time is used.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApiInterface
     */
    getSubscriptionGet(subscriptionId: string, at?: string, options?: RawAxiosRequestConfig): AxiosPromise<SubscriptionExpanded>;

    /**
     * List all addons of a subscription. In the returned list will match to a set unique by addonId.
     * @summary List subscription addons
     * @param {string} subscriptionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApiInterface
     */
    listSubscriptionAddons(subscriptionId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<SubscriptionAddon>>;

    /**
     * Lists all subscriptions for the current namespace. Optionally filter by customer or status.
     * @summary List subscriptions
     * @param {string} [customerId] Filter by customer ID.
     * @param {Array<SubscriptionStatus>} [status] 
     * @param {SortOrder} [order] The order direction.
     * @param {CustomerSubscriptionOrderBy} [orderBy] The order by field.
     * @param {number} [page] Page index.  Default is 1.
     * @param {number} [pageSize] The maximum number of items per page.  Default is 100.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApiInterface
     */
    listSubscriptions(customerId?: string, status?: Array<SubscriptionStatus>, order?: SortOrder, orderBy?: CustomerSubscriptionOrderBy, page?: number, pageSize?: number, options?: RawAxiosRequestConfig): AxiosPromise<SubscriptionPaginatedResponse>;

    /**
     * Migrates the subscripiton to the provided version of the current plan. If possible, the migration will be done immediately. If not, the migration will be scheduled to the end of the current billing period.
     * @summary Migrate subscription
     * @param {string} subscriptionId 
     * @param {MigrateSubscriptionRequest} migrateSubscriptionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApiInterface
     */
    migrateSubscription(subscriptionId: string, migrateSubscriptionRequest: MigrateSubscriptionRequest, options?: RawAxiosRequestConfig): AxiosPromise<SubscriptionChangeResponseBody>;

    /**
     * Restores a canceled subscription. Any subscription scheduled to start later will be deleted and this subscription will be continued indefinitely.
     * @summary Restore subscription
     * @param {string} subscriptionId 
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     * @memberof SubscriptionsApiInterface
     */
    restoreSubscription(subscriptionId: string, options?: RawAxiosRequestConfig): AxiosPromise<Subscription>;

    /**
     * Cancels the scheduled cancelation.
     * @summary Unschedule cancelation
     * @param {string} subscriptionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApiInterface
     */
    unscheduleCancelation(subscriptionId: string, options?: RawAxiosRequestConfig): AxiosPromise<Subscription>;

    /**
     * Updates a subscription addon (allows changing the quantity: purchasing more instances or cancelling the current instances)
     * @summary Update subscription addon
     * @param {string} subscriptionId 
     * @param {string} subscriptionAddonId 
     * @param {SubscriptionAddonUpdate} subscriptionAddonUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApiInterface
     */
    updateSubscriptionAddon(subscriptionId: string, subscriptionAddonId: string, subscriptionAddonUpdate: SubscriptionAddonUpdate, options?: RawAxiosRequestConfig): AxiosPromise<SubscriptionAddon>;

}

/**
 * SubscriptionsApi - object-oriented interface
 * @export
 * @class SubscriptionsApi
 * @extends {BaseAPI}
 */
export class SubscriptionsApi extends BaseAPI implements SubscriptionsApiInterface {
    /**
     * Cancels the subscription. Will result in a scheduling conflict if there are other subscriptions scheduled to start after the cancellation time.
     * @summary Cancel subscription
     * @param {string} subscriptionId 
     * @param {CancelSubscriptionRequest} cancelSubscriptionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApi
     */
    public cancelSubscription(subscriptionId: string, cancelSubscriptionRequest: CancelSubscriptionRequest, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).cancelSubscription(subscriptionId, cancelSubscriptionRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Closes a running subscription and starts a new one according to the specification. Can be used for upgrades, downgrades, and plan changes.
     * @summary Change subscription
     * @param {string} subscriptionId 
     * @param {SubscriptionChange} subscriptionChange 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApi
     */
    public changeSubscription(subscriptionId: string, subscriptionChange: SubscriptionChange, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).changeSubscription(subscriptionId, subscriptionChange, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create subscription
     * @param {SubscriptionCreate} subscriptionCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApi
     */
    public createSubscription(subscriptionCreate: SubscriptionCreate, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).createSubscription(subscriptionCreate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a new subscription addon, either providing the key or the id of the addon.
     * @summary Create subscription addon
     * @param {string} subscriptionId 
     * @param {SubscriptionAddonCreate} subscriptionAddonCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApi
     */
    public createSubscriptionAddon(subscriptionId: string, subscriptionAddonCreate: SubscriptionAddonCreate, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).createSubscriptionAddon(subscriptionId, subscriptionAddonCreate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Deletes a subscription. Only scheduled subscriptions can be deleted.
     * @summary Delete subscription
     * @param {string} subscriptionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApi
     */
    public deleteSubscription(subscriptionId: string, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).deleteSubscription(subscriptionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Batch processing commands for manipulating running subscriptions. The key format is `/phases/{phaseKey}` or `/phases/{phaseKey}/items/{itemKey}`.
     * @summary Edit subscription
     * @param {string} subscriptionId 
     * @param {SubscriptionEdit} subscriptionEdit 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApi
     */
    public editSubscription(subscriptionId: string, subscriptionEdit: SubscriptionEdit, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).editSubscription(subscriptionId, subscriptionEdit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get a subscription addon by id.
     * @summary Get subscription addon
     * @param {string} subscriptionId 
     * @param {string} subscriptionAddonId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApi
     */
    public getSubscriptionAddon(subscriptionId: string, subscriptionAddonId: string, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).getSubscriptionAddon(subscriptionId, subscriptionAddonId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get subscription
     * @param {string} subscriptionId 
     * @param {string} [at] The time at which the subscription should be queried. If not provided the current time is used.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApi
     */
    public getSubscriptionGet(subscriptionId: string, at?: string, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).getSubscriptionGet(subscriptionId, at, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List all addons of a subscription. In the returned list will match to a set unique by addonId.
     * @summary List subscription addons
     * @param {string} subscriptionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApi
     */
    public listSubscriptionAddons(subscriptionId: string, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).listSubscriptionAddons(subscriptionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Lists all subscriptions for the current namespace. Optionally filter by customer or status.
     * @summary List subscriptions
     * @param {string} [customerId] Filter by customer ID.
     * @param {Array<SubscriptionStatus>} [status] 
     * @param {SortOrder} [order] The order direction.
     * @param {CustomerSubscriptionOrderBy} [orderBy] The order by field.
     * @param {number} [page] Page index.  Default is 1.
     * @param {number} [pageSize] The maximum number of items per page.  Default is 100.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApi
     */
    public listSubscriptions(customerId?: string, status?: Array<SubscriptionStatus>, order?: SortOrder, orderBy?: CustomerSubscriptionOrderBy, page?: number, pageSize?: number, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).listSubscriptions(customerId, status, order, orderBy, page, pageSize, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Migrates the subscripiton to the provided version of the current plan. If possible, the migration will be done immediately. If not, the migration will be scheduled to the end of the current billing period.
     * @summary Migrate subscription
     * @param {string} subscriptionId 
     * @param {MigrateSubscriptionRequest} migrateSubscriptionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApi
     */
    public migrateSubscription(subscriptionId: string, migrateSubscriptionRequest: MigrateSubscriptionRequest, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).migrateSubscription(subscriptionId, migrateSubscriptionRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Restores a canceled subscription. Any subscription scheduled to start later will be deleted and this subscription will be continued indefinitely.
     * @summary Restore subscription
     * @param {string} subscriptionId 
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     * @memberof SubscriptionsApi
     */
    public restoreSubscription(subscriptionId: string, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).restoreSubscription(subscriptionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Cancels the scheduled cancelation.
     * @summary Unschedule cancelation
     * @param {string} subscriptionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApi
     */
    public unscheduleCancelation(subscriptionId: string, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).unscheduleCancelation(subscriptionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates a subscription addon (allows changing the quantity: purchasing more instances or cancelling the current instances)
     * @summary Update subscription addon
     * @param {string} subscriptionId 
     * @param {string} subscriptionAddonId 
     * @param {SubscriptionAddonUpdate} subscriptionAddonUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionsApi
     */
    public updateSubscriptionAddon(subscriptionId: string, subscriptionAddonId: string, subscriptionAddonUpdate: SubscriptionAddonUpdate, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).updateSubscriptionAddon(subscriptionId, subscriptionAddonId, subscriptionAddonUpdate, options).then((request) => request(this.axios, this.basePath));
    }
}

