/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { TenantConfigResponse } from '../models';
/**
 * TenantConfigApi - axios parameter creator
 * @export
 */
export const TenantConfigApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Return the authenticated tenant\'s region and regional endpoints.  SDKs call this once at startup to discover which ingest endpoint to use. The response is cacheable for 1 hour.
         * @summary Get tenant regional config for SDK auto-discovery
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTenantConfig: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/tenant/config`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TenantConfigApi - functional programming interface
 * @export
 */
export const TenantConfigApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TenantConfigApiAxiosParamCreator(configuration)
    return {
        /**
         * Return the authenticated tenant\'s region and regional endpoints.  SDKs call this once at startup to discover which ingest endpoint to use. The response is cacheable for 1 hour.
         * @summary Get tenant regional config for SDK auto-discovery
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTenantConfig(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TenantConfigResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTenantConfig(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TenantConfigApi.getTenantConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TenantConfigApi - factory interface
 * @export
 */
export const TenantConfigApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TenantConfigApiFp(configuration)
    return {
        /**
         * Return the authenticated tenant\'s region and regional endpoints.  SDKs call this once at startup to discover which ingest endpoint to use. The response is cacheable for 1 hour.
         * @summary Get tenant regional config for SDK auto-discovery
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTenantConfig(options?: RawAxiosRequestConfig): AxiosPromise<TenantConfigResponse> {
            return localVarFp.getTenantConfig(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TenantConfigApi - interface
 * @export
 * @interface TenantConfigApi
 */
export interface TenantConfigApiInterface {
    /**
     * Return the authenticated tenant\'s region and regional endpoints.  SDKs call this once at startup to discover which ingest endpoint to use. The response is cacheable for 1 hour.
     * @summary Get tenant regional config for SDK auto-discovery
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantConfigApiInterface
     */
    getTenantConfig(options?: RawAxiosRequestConfig): AxiosPromise<TenantConfigResponse>;

}

/**
 * TenantConfigApi - object-oriented interface
 * @export
 * @class TenantConfigApi
 * @extends {BaseAPI}
 */
export class TenantConfigApi extends BaseAPI implements TenantConfigApiInterface {
    /**
     * Return the authenticated tenant\'s region and regional endpoints.  SDKs call this once at startup to discover which ingest endpoint to use. The response is cacheable for 1 hour.
     * @summary Get tenant regional config for SDK auto-discovery
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantConfigApi
     */
    public getTenantConfig(options?: RawAxiosRequestConfig) {
        return TenantConfigApiFp(this.configuration).getTenantConfig(options).then((request) => request(this.axios, this.basePath));
    }
}

