/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Response from trigger check.
 * @export
 * @interface AppApiV1AutoTopupRouterTriggerResponse
 */
export interface AppApiV1AutoTopupRouterTriggerResponse {
    /**
     * 
     * @type {boolean}
     * @memberof AppApiV1AutoTopupRouterTriggerResponse
     */
    'triggered': boolean;
    /**
     * 
     * @type {string}
     * @memberof AppApiV1AutoTopupRouterTriggerResponse
     */
    'reason'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppApiV1AutoTopupRouterTriggerResponse
     */
    'rule_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppApiV1AutoTopupRouterTriggerResponse
     */
    'wallet_id'?: string;
    /**
     * 
     * @type {number}
     * @memberof AppApiV1AutoTopupRouterTriggerResponse
     */
    'topup_amount_micros'?: number;
    /**
     * 
     * @type {string}
     * @memberof AppApiV1AutoTopupRouterTriggerResponse
     */
    'payment_method_ref'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppApiV1AutoTopupRouterTriggerResponse
     */
    'invoice_mode'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppApiV1AutoTopupRouterTriggerResponse
     */
    'outbox_event_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppApiV1AutoTopupRouterTriggerResponse
     */
    'cooldown_until'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppApiV1AutoTopupRouterTriggerResponse
     */
    'wallet_state'?: string;
    /**
     * 
     * @type {number}
     * @memberof AppApiV1AutoTopupRouterTriggerResponse
     */
    'available_balance_micros'?: number;
}

