/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.0.0-rc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CustomInvoicingAppReplaceUpdate } from './custom-invoicing-app-replace-update';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxAppReplaceUpdate } from './sandbox-app-replace-update';
// May contain unused imports in some cases
// @ts-ignore
import type { StripeAppReplaceUpdate } from './stripe-app-replace-update';

/**
 * @type AppReplaceUpdate
 * App ReplaceUpdate Model
 * @export
 */
export type AppReplaceUpdate = { type: 'custom_invoicing' } & CustomInvoicingAppReplaceUpdate | { type: 'sandbox' } & SandboxAppReplaceUpdate | { type: 'stripe' } & StripeAppReplaceUpdate;


