/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AskCustomerRequest
 */
export interface AskCustomerRequest {
    /**
     * 
     * @type {string}
     * @memberof AskCustomerRequest
     */
    'missing_field': AskCustomerRequestMissingFieldEnum;
    /**
     * 
     * @type {string}
     * @memberof AskCustomerRequest
     */
    'context'?: string;
}

export const AskCustomerRequestMissingFieldEnum = {
    Date: 'date',
    Amount: 'amount',
    InvoiceRef: 'invoice_ref',
    Other: 'other'
} as const;

export type AskCustomerRequestMissingFieldEnum = typeof AskCustomerRequestMissingFieldEnum[keyof typeof AskCustomerRequestMissingFieldEnum];


