/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.0.0-rc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Period } from './period';

/**
 * The balance history window.
 * @export
 * @interface BalanceHistoryWindow
 */
export interface BalanceHistoryWindow {
    /**
     * 
     * @type {Period}
     * @memberof BalanceHistoryWindow
     */
    'period': Period;
    /**
     * The total usage of the feature in the period.
     * @type {number}
     * @memberof BalanceHistoryWindow
     */
    'usage': number;
    /**
     * The entitlement balance at the start of the period.
     * @type {number}
     * @memberof BalanceHistoryWindow
     */
    'balanceAtStart': number;
}

