/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.0.0-rc4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * BillingProfileExpand details what profile fields to expand
 * @export
 * @enum {string}
 */

export const BillingProfileExpand = {
    Apps: 'apps'
} as const;

export type BillingProfileExpand = typeof BillingProfileExpand[keyof typeof BillingProfileExpand];



