/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * BillingWorkflowCollectionAlignmentSubscription specifies the alignment for collecting the pending line items into an invoice.
 * @export
 * @interface BillingWorkflowCollectionAlignmentSubscription
 */
export interface BillingWorkflowCollectionAlignmentSubscription {
    /**
     * The type of alignment.
     * @type {string}
     * @memberof BillingWorkflowCollectionAlignmentSubscription
     */
    'type': BillingWorkflowCollectionAlignmentSubscriptionTypeEnum;
}

export const BillingWorkflowCollectionAlignmentSubscriptionTypeEnum = {
    Subscription: 'subscription'
} as const;

export type BillingWorkflowCollectionAlignmentSubscriptionTypeEnum = typeof BillingWorkflowCollectionAlignmentSubscriptionTypeEnum[keyof typeof BillingWorkflowCollectionAlignmentSubscriptionTypeEnum];


