/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BillingProfile } from './billing-profile';

/**
 * Paginated response
 * @export
 * @interface BillingProfilePaginatedResponse
 */
export interface BillingProfilePaginatedResponse {
    /**
     * The total number of items.
     * @type {number}
     * @memberof BillingProfilePaginatedResponse
     */
    'totalCount': number;
    /**
     * The page index.
     * @type {number}
     * @memberof BillingProfilePaginatedResponse
     */
    'page': number;
    /**
     * The maximum number of items per page.
     * @type {number}
     * @memberof BillingProfilePaginatedResponse
     */
    'pageSize': number;
    /**
     * The items in the current page.
     * @type {Array<BillingProfile>}
     * @memberof BillingProfilePaginatedResponse
     */
    'items': Array<BillingProfile>;
}

