/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BomComponentOut
 */
export interface BomComponentOut {
    /**
     * 
     * @type {string}
     * @memberof BomComponentOut
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof BomComponentOut
     */
    'component_type': string;
    /**
     * 
     * @type {string}
     * @memberof BomComponentOut
     */
    'provider': string;
    /**
     * 
     * @type {string}
     * @memberof BomComponentOut
     */
    'model': string;
    /**
     * 
     * @type {string}
     * @memberof BomComponentOut
     */
    'metric_type': string;
    /**
     * 
     * @type {number}
     * @memberof BomComponentOut
     */
    'expected_quantity': number;
    /**
     * 
     * @type {number}
     * @memberof BomComponentOut
     */
    'expected_span_count': number;
    /**
     * 
     * @type {number}
     * @memberof BomComponentOut
     */
    'unit_cost': number;
    /**
     * 
     * @type {number}
     * @memberof BomComponentOut
     */
    'standard_cost': number;
    /**
     * 
     * @type {string}
     * @memberof BomComponentOut
     */
    'currency': string;
    /**
     * 
     * @type {number}
     * @memberof BomComponentOut
     */
    'sort_order': number;
    /**
     * 
     * @type {string}
     * @memberof BomComponentOut
     */
    'notes': string;
}

