/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CheckoutSessionCustomTextAfterSubmitParamsAfterSubmit } from './checkout-session-custom-text-after-submit-params-after-submit';
// May contain unused imports in some cases
// @ts-ignore
import type { CheckoutSessionCustomTextAfterSubmitParamsShippingAddress } from './checkout-session-custom-text-after-submit-params-shipping-address';
// May contain unused imports in some cases
// @ts-ignore
import type { CheckoutSessionCustomTextAfterSubmitParamsSubmit } from './checkout-session-custom-text-after-submit-params-submit';
// May contain unused imports in some cases
// @ts-ignore
import type { CheckoutSessionCustomTextAfterSubmitParamsTermsOfServiceAcceptance } from './checkout-session-custom-text-after-submit-params-terms-of-service-acceptance';

/**
 * Stripe CheckoutSession.custom_text
 * @export
 * @interface CheckoutSessionCustomTextAfterSubmitParams
 */
export interface CheckoutSessionCustomTextAfterSubmitParams {
    /**
     * 
     * @type {CheckoutSessionCustomTextAfterSubmitParamsAfterSubmit}
     * @memberof CheckoutSessionCustomTextAfterSubmitParams
     */
    'afterSubmit'?: CheckoutSessionCustomTextAfterSubmitParamsAfterSubmit;
    /**
     * 
     * @type {CheckoutSessionCustomTextAfterSubmitParamsShippingAddress}
     * @memberof CheckoutSessionCustomTextAfterSubmitParams
     */
    'shippingAddress'?: CheckoutSessionCustomTextAfterSubmitParamsShippingAddress;
    /**
     * 
     * @type {CheckoutSessionCustomTextAfterSubmitParamsSubmit}
     * @memberof CheckoutSessionCustomTextAfterSubmitParams
     */
    'submit'?: CheckoutSessionCustomTextAfterSubmitParamsSubmit;
    /**
     * 
     * @type {CheckoutSessionCustomTextAfterSubmitParamsTermsOfServiceAcceptance}
     * @memberof CheckoutSessionCustomTextAfterSubmitParams
     */
    'termsOfServiceAcceptance'?: CheckoutSessionCustomTextAfterSubmitParamsTermsOfServiceAcceptance;
}

