/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * PATCH /contacts/{id} — partial update.
 * @export
 * @interface ContactUpdate
 */
export interface ContactUpdate {
    /**
     * 
     * @type {string}
     * @memberof ContactUpdate
     */
    'full_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactUpdate
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactUpdate
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactUpdate
     */
    'role'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ContactUpdate
     */
    'is_primary_ap'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ContactUpdate
     */
    'is_active'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ContactUpdate
     */
    'locale'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactUpdate
     */
    'timezone'?: string;
}

