/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.2.0-rc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request to create a balance snapshot.
 * @export
 * @interface CreateSnapshotRequest
 */
export interface CreateSnapshotRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof CreateSnapshotRequest
     */
    'tenant_id': string;
    /**
     * Pool identifier
     * @type {string}
     * @memberof CreateSnapshotRequest
     */
    'pool_id': string;
    /**
     * Wallet identifier
     * @type {string}
     * @memberof CreateSnapshotRequest
     */
    'wallet_id': string;
    /**
     * Effective timestamp for balance calculation
     * @type {string}
     * @memberof CreateSnapshotRequest
     */
    'as_of_effective_at': string;
    /**
     * 
     * @type {string}
     * @memberof CreateSnapshotRequest
     */
    'as_of_recorded_at'?: string | null;
    /**
     * Transaction isolation level
     * @type {string}
     * @memberof CreateSnapshotRequest
     */
    'isolation_level'?: string;
}

