/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.1.0-rc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Create Stripe checkout session consent collection terms of service.
 * @export
 * @enum {string}
 */

export const CreateStripeCheckoutSessionConsentCollectionTermsOfService = {
    None: 'none',
    Required: 'required'
} as const;

export type CreateStripeCheckoutSessionConsentCollectionTermsOfService = typeof CreateStripeCheckoutSessionConsentCollectionTermsOfService[keyof typeof CreateStripeCheckoutSessionConsentCollectionTermsOfService];



