/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.0.0-rc6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EntitlementValue } from './entitlement-value';

/**
 * CustomerAccess describes what features the customer has access to.
 * @export
 * @interface CustomerAccess
 */
export interface CustomerAccess {
    /**
     * Map of entitlements the customer has access to. The key is the feature key, the value is the entitlement value + the entitlement ID.
     * @type {{ [key: string]: EntitlementValue; }}
     * @memberof CustomerAccess
     */
    'entitlements': { [key: string]: EntitlementValue; };
}

