/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Mapping to attribute metered usage to the customer. One customer can have zero or more subjects, but one subject can only belong to one customer.
 * @export
 * @interface CustomerUsageAttribution
 */
export interface CustomerUsageAttribution {
    /**
     * The subjects that are attributed to the customer. Can be empty when no subjects are associated with the customer.
     * @type {Array<string>}
     * @memberof CustomerUsageAttribution
     */
    'subjectKeys': Array<string>;
}

