/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.0.0-rc6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Order by options for customer subscriptions.
 * @export
 * @enum {string}
 */

export const CustomerSubscriptionOrderBy = {
    ActiveFrom: 'activeFrom',
    ActiveTo: 'activeTo'
} as const;

export type CustomerSubscriptionOrderBy = typeof CustomerSubscriptionOrderBy[keyof typeof CustomerSubscriptionOrderBy];



