/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.1.0-rc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CommercialOverrides } from './commercial-overrides';
// May contain unused imports in some cases
// @ts-ignore
import type { CustomPlanInput } from './custom-plan-input';
// May contain unused imports in some cases
// @ts-ignore
import type { SubscriptionTiming } from './subscription-timing';

/**
 * Change a custom subscription.
 * @export
 * @interface CustomSubscriptionChange
 */
export interface CustomSubscriptionChange {
    /**
     * Timing configuration for the change, when the change should take effect. For changing a subscription, the accepted values depend on the subscription configuration.
     * @type {SubscriptionTiming}
     * @memberof CustomSubscriptionChange
     */
    'timing': SubscriptionTiming;
    /**
     * The billing anchor of the subscription. The provided date will be normalized according to the billing cadence to the nearest recurrence before start time. If not provided, the previous subscription billing anchor will be used.
     * @type {string}
     * @memberof CustomSubscriptionChange
     */
    'billingAnchor'?: string;
    /**
     * Commercial terms for this subscription change.
     * @type {CommercialOverrides}
     * @memberof CustomSubscriptionChange
     */
    'commercialOverrides'?: CommercialOverrides;
    /**
     * The custom plan description which defines the Subscription.
     * @type {CustomPlanInput}
     * @memberof CustomSubscriptionChange
     */
    'customPlan': CustomPlanInput;
}

