/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.0.0-rc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Address } from './address';
// May contain unused imports in some cases
// @ts-ignore
import type { CustomerUsageAttribution } from './customer-usage-attribution';

/**
 * Resource update operation model.
 * @export
 * @interface CustomerReplaceUpdate
 */
export interface CustomerReplaceUpdate {
    /**
     * Human-readable name for the resource. Between 1 and 256 characters.
     * @type {string}
     * @memberof CustomerReplaceUpdate
     */
    'name': string;
    /**
     * Optional description of the resource. Maximum 1024 characters.
     * @type {string}
     * @memberof CustomerReplaceUpdate
     */
    'description'?: string;
    /**
     * Additional metadata for the resource.
     * @type {{ [key: string]: string; }}
     * @memberof CustomerReplaceUpdate
     */
    'metadata'?: { [key: string]: string; };
    /**
     * An optional unique key of the customer. Useful to reference the customer in external systems. For example, your database ID.
     * @type {string}
     * @memberof CustomerReplaceUpdate
     */
    'key'?: string;
    /**
     * Mapping to attribute metered usage to the customer
     * @type {CustomerUsageAttribution}
     * @memberof CustomerReplaceUpdate
     */
    'usageAttribution': CustomerUsageAttribution;
    /**
     * The primary email address of the customer.
     * @type {string}
     * @memberof CustomerReplaceUpdate
     */
    'primaryEmail'?: string;
    /**
     * Currency of the customer. Used for billing, tax and invoicing.
     * @type {string}
     * @memberof CustomerReplaceUpdate
     */
    'currency'?: string;
    /**
     * The billing address of the customer. Used for tax and invoicing.
     * @type {Address}
     * @memberof CustomerReplaceUpdate
     */
    'billingAddress'?: Address;
}

