/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The reason for the discount is a maximum spend.
 * @export
 * @interface DiscountReasonMaximumSpend
 */
export interface DiscountReasonMaximumSpend {
    /**
     * 
     * @type {string}
     * @memberof DiscountReasonMaximumSpend
     */
    'type': DiscountReasonMaximumSpendTypeEnum;
}

export const DiscountReasonMaximumSpendTypeEnum = {
    MaximumSpend: 'maximum_spend'
} as const;

export type DiscountReasonMaximumSpendTypeEnum = typeof DiscountReasonMaximumSpendTypeEnum[keyof typeof DiscountReasonMaximumSpendTypeEnum];


