/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.1.0-rc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RateCard } from './rate-card';

/**
 * Add a new item to a phase.
 * @export
 * @interface EditSubscriptionAddItem
 */
export interface EditSubscriptionAddItem {
    /**
     * 
     * @type {string}
     * @memberof EditSubscriptionAddItem
     */
    'op': EditSubscriptionAddItemOpEnum;
    /**
     * 
     * @type {string}
     * @memberof EditSubscriptionAddItem
     */
    'phaseKey': string;
    /**
     * 
     * @type {RateCard}
     * @memberof EditSubscriptionAddItem
     */
    'rateCard': RateCard;
}

export const EditSubscriptionAddItemOpEnum = {
    AddItem: 'add_item'
} as const;

export type EditSubscriptionAddItemOpEnum = typeof EditSubscriptionAddItemOpEnum[keyof typeof EditSubscriptionAddItemOpEnum];


