/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EntitlementBooleanCreateInputs } from './entitlement-boolean-create-inputs';
// May contain unused imports in some cases
// @ts-ignore
import type { EntitlementGrantCreateInputV2 } from './entitlement-grant-create-input-v2';
// May contain unused imports in some cases
// @ts-ignore
import type { EntitlementMeteredV2CreateInputs } from './entitlement-metered-v2-create-inputs';
// May contain unused imports in some cases
// @ts-ignore
import type { EntitlementStaticCreateInputs } from './entitlement-static-create-inputs';
// May contain unused imports in some cases
// @ts-ignore
import type { IssueAfterReset } from './issue-after-reset';
// May contain unused imports in some cases
// @ts-ignore
import type { MeasureUsageFrom } from './measure-usage-from';
// May contain unused imports in some cases
// @ts-ignore
import type { RecurringPeriodCreateInput } from './recurring-period-create-input';

/**
 * @type EntitlementV2CreateInputs
 * Create inputs for entitlement
 * @export
 */
export type EntitlementV2CreateInputs = { type: 'boolean' } & EntitlementBooleanCreateInputs | { type: 'metered' } & EntitlementMeteredV2CreateInputs | { type: 'static' } & EntitlementStaticCreateInputs;


