/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EntitlementBoolean } from './entitlement-boolean';
// May contain unused imports in some cases
// @ts-ignore
import type { EntitlementMetered } from './entitlement-metered';
// May contain unused imports in some cases
// @ts-ignore
import type { EntitlementStatic } from './entitlement-static';
// May contain unused imports in some cases
// @ts-ignore
import type { Period } from './period';
// May contain unused imports in some cases
// @ts-ignore
import type { RecurringPeriod } from './recurring-period';

/**
 * @type Entitlement
 * Entitlement templates are used to define the entitlements of a plan. Features are omitted from the entitlement template, as they are defined in the rate card.
 * @export
 */
export type Entitlement = { type: 'boolean' } & EntitlementBoolean | { type: 'metered' } & EntitlementMetered | { type: 'static' } & EntitlementStatic;


