/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FeatureFlagItem
 */
export interface FeatureFlagItem {
    /**
     * 
     * @type {string}
     * @memberof FeatureFlagItem
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof FeatureFlagItem
     */
    'name': string;
    /**
     * 
     * @type {boolean}
     * @memberof FeatureFlagItem
     */
    'tenant_override': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FeatureFlagItem
     */
    'default_value': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FeatureFlagItem
     */
    'enabled': boolean;
    /**
     * 
     * @type {string}
     * @memberof FeatureFlagItem
     */
    'last_changed': string;
}

