/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.2.0-rc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Limited representation of a feature resource which includes only its unique identifiers (id, key).
 * @export
 * @interface FeatureMeta
 */
export interface FeatureMeta {
    /**
     * Unique identifier of a feature.
     * @type {string}
     * @memberof FeatureMeta
     */
    'id': string;
    /**
     * The key is an immutable unique identifier of the feature used throughout the API, for example when interacting with a subject\'s entitlements.
     * @type {string}
     * @memberof FeatureMeta
     */
    'key': string;
}

