/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.0.0-rc6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A filter for a string field.
 * @export
 * @interface FilterString
 */
export interface FilterString {
    /**
     * The field must be equal to the provided value.
     * @type {string}
     * @memberof FilterString
     */
    '$eq'?: string;
    /**
     * The field must not be equal to the provided value.
     * @type {string}
     * @memberof FilterString
     */
    '$ne'?: string;
    /**
     * The field must be in the provided list of values.
     * @type {Array<string>}
     * @memberof FilterString
     */
    '$in'?: Array<string>;
    /**
     * The field must not be in the provided list of values.
     * @type {Array<string>}
     * @memberof FilterString
     */
    '$nin'?: Array<string>;
    /**
     * The field must match the provided value.
     * @type {string}
     * @memberof FilterString
     */
    '$like'?: string;
    /**
     * The field must not match the provided value.
     * @type {string}
     * @memberof FilterString
     */
    '$nlike'?: string;
    /**
     * The field must match the provided value, ignoring case.
     * @type {string}
     * @memberof FilterString
     */
    '$ilike'?: string;
    /**
     * The field must not match the provided value, ignoring case.
     * @type {string}
     * @memberof FilterString
     */
    '$nilike'?: string;
    /**
     * The field must be greater than the provided value.
     * @type {string}
     * @memberof FilterString
     */
    '$gt'?: string;
    /**
     * The field must be greater than or equal to the provided value.
     * @type {string}
     * @memberof FilterString
     */
    '$gte'?: string;
    /**
     * The field must be less than the provided value.
     * @type {string}
     * @memberof FilterString
     */
    '$lt'?: string;
    /**
     * The field must be less than or equal to the provided value.
     * @type {string}
     * @memberof FilterString
     */
    '$lte'?: string;
    /**
     * Provide a list of filters to be combined with a logical AND.
     * @type {Array<FilterString>}
     * @memberof FilterString
     */
    '$and'?: Array<FilterString>;
    /**
     * Provide a list of filters to be combined with a logical OR.
     * @type {Array<FilterString>}
     * @memberof FilterString
     */
    '$or'?: Array<FilterString>;
}

