/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GateStatusResponse
 */
export interface GateStatusResponse {
    /**
     * 
     * @type {string}
     * @memberof GateStatusResponse
     */
    'gate_status': string;
    /**
     * 
     * @type {number}
     * @memberof GateStatusResponse
     */
    'wape': number;
    /**
     * 
     * @type {boolean}
     * @memberof GateStatusResponse
     */
    'wape_pass': boolean;
    /**
     * 
     * @type {number}
     * @memberof GateStatusResponse
     */
    'wape_threshold': number;
    /**
     * 
     * @type {number}
     * @memberof GateStatusResponse
     */
    'coverage_pct': number;
    /**
     * 
     * @type {boolean}
     * @memberof GateStatusResponse
     */
    'coverage_pass': boolean;
    /**
     * 
     * @type {number}
     * @memberof GateStatusResponse
     */
    'coverage_threshold': number;
    /**
     * 
     * @type {string}
     * @memberof GateStatusResponse
     */
    'shadow_run_id': string;
    /**
     * 
     * @type {string}
     * @memberof GateStatusResponse
     */
    'evaluated_at': string;
}

