/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.1.0-rc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request to get FX rate at a timestamp.
 * @export
 * @interface GetFxRateRequest
 */
export interface GetFxRateRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof GetFxRateRequest
     */
    'tenant_id': string;
    /**
     * Pool identifier
     * @type {string}
     * @memberof GetFxRateRequest
     */
    'pool_id': string;
    /**
     * Timestamp to get rate for
     * @type {string}
     * @memberof GetFxRateRequest
     */
    'as_of': string;
}

