/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CommercialOverridesPayload } from './commercial-overrides-payload';
// May contain unused imports in some cases
// @ts-ignore
import type { CreditConfigPayload } from './credit-config-payload';
// May contain unused imports in some cases
// @ts-ignore
import type { EntitlementPayload } from './entitlement-payload';

/**
 * 
 * @export
 * @interface GrantPlanChangeRequest
 */
export interface GrantPlanChangeRequest {
    /**
     * 
     * @type {string}
     * @memberof GrantPlanChangeRequest
     */
    'tenant_id': string;
    /**
     * 
     * @type {string}
     * @memberof GrantPlanChangeRequest
     */
    'subscription_id': string;
    /**
     * 
     * @type {string}
     * @memberof GrantPlanChangeRequest
     */
    'customer_id': string;
    /**
     * 
     * @type {string}
     * @memberof GrantPlanChangeRequest
     */
    'oldPlanId': string;
    /**
     * 
     * @type {number}
     * @memberof GrantPlanChangeRequest
     */
    'oldPlanVersion': number;
    /**
     * 
     * @type {string}
     * @memberof GrantPlanChangeRequest
     */
    'newPlanId': string;
    /**
     * 
     * @type {number}
     * @memberof GrantPlanChangeRequest
     */
    'newPlanVersion': number;
    /**
     * 
     * @type {string}
     * @memberof GrantPlanChangeRequest
     */
    'effectiveAt': string;
    /**
     * 
     * @type {CreditConfigPayload}
     * @memberof GrantPlanChangeRequest
     */
    'newCreditConfig': CreditConfigPayload;
    /**
     * 
     * @type {CommercialOverridesPayload}
     * @memberof GrantPlanChangeRequest
     */
    'commercial_overrides'?: CommercialOverridesPayload;
    /**
     * 
     * @type {Array<EntitlementPayload>}
     * @memberof GrantPlanChangeRequest
     */
    'entitlements': Array<EntitlementPayload>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GrantPlanChangeRequest
     */
    'subject_keys': Array<string>;
}

