/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * One promise-to-pay row for bulk import.  ``external_ptp_id`` is the upstream identifier (e.g. Growfin PTP number) and the upsert key.  ``case_id`` must point at a non-terminal case.
 * @export
 * @interface ImportPromiseItem
 */
export interface ImportPromiseItem {
    /**
     * 
     * @type {string}
     * @memberof ImportPromiseItem
     */
    'external_ptp_id': string;
    /**
     * 
     * @type {string}
     * @memberof ImportPromiseItem
     */
    'case_id': string;
    /**
     * 
     * @type {string}
     * @memberof ImportPromiseItem
     */
    'contact_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ImportPromiseItem
     */
    'invoice_id'?: string;
    /**
     * 
     * @type {number}
     * @memberof ImportPromiseItem
     */
    'promised_amount_micros': number;
    /**
     * 
     * @type {number}
     * @memberof ImportPromiseItem
     */
    'fulfilled_amount_micros'?: number;
    /**
     * 
     * @type {string}
     * @memberof ImportPromiseItem
     */
    'currency_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof ImportPromiseItem
     */
    'promised_date': string;
    /**
     * 
     * @type {string}
     * @memberof ImportPromiseItem
     */
    'status'?: ImportPromiseItemStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ImportPromiseItem
     */
    'captured_from_channel'?: ImportPromiseItemCapturedFromChannelEnum;
    /**
     * 
     * @type {string}
     * @memberof ImportPromiseItem
     */
    'captured_by'?: ImportPromiseItemCapturedByEnum;
    /**
     * 
     * @type {number}
     * @memberof ImportPromiseItem
     */
    'confidence'?: number;
    /**
     * 
     * @type {string}
     * @memberof ImportPromiseItem
     */
    'ptp_no'?: string;
    /**
     * 
     * @type {number}
     * @memberof ImportPromiseItem
     */
    'balance_amount_micros'?: number;
    /**
     * 
     * @type {number}
     * @memberof ImportPromiseItem
     */
    'amount_base_currency_micros'?: number;
    /**
     * 
     * @type {number}
     * @memberof ImportPromiseItem
     */
    'balance_amount_base_currency_micros'?: number;
    /**
     * 
     * @type {number}
     * @memberof ImportPromiseItem
     */
    'slippage_count'?: number;
    /**
     * 
     * @type {string}
     * @memberof ImportPromiseItem
     */
    'source_app'?: string;
    /**
     * 
     * @type {string}
     * @memberof ImportPromiseItem
     */
    'ptp_type'?: string;
}

export const ImportPromiseItemStatusEnum = {
    Open: 'open',
    Fulfilled: 'fulfilled',
    Broken: 'broken',
    Cancelled: 'cancelled',
    Superseded: 'superseded'
} as const;

export type ImportPromiseItemStatusEnum = typeof ImportPromiseItemStatusEnum[keyof typeof ImportPromiseItemStatusEnum];
export const ImportPromiseItemCapturedFromChannelEnum = {
    Email: 'email',
    Sms: 'sms',
    Phone: 'phone',
    Portal: 'portal',
    HumanNote: 'human_note',
    AgentDetected: 'agent_detected'
} as const;

export type ImportPromiseItemCapturedFromChannelEnum = typeof ImportPromiseItemCapturedFromChannelEnum[keyof typeof ImportPromiseItemCapturedFromChannelEnum];
export const ImportPromiseItemCapturedByEnum = {
    Customer: 'customer',
    Human: 'human',
    Agent: 'agent'
} as const;

export type ImportPromiseItemCapturedByEnum = typeof ImportPromiseItemCapturedByEnum[keyof typeof ImportPromiseItemCapturedByEnum];


