/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CloudCostRowInput } from './cloud-cost-row-input';

/**
 * 
 * @export
 * @interface ImportBatchRequest
 */
export interface ImportBatchRequest {
    /**
     * \'aws\', \'gcp\', or \'azure\'
     * @type {string}
     * @memberof ImportBatchRequest
     */
    'cloud_provider': string;
    /**
     * 
     * @type {string}
     * @memberof ImportBatchRequest
     */
    'billing_period_start': string;
    /**
     * 
     * @type {string}
     * @memberof ImportBatchRequest
     */
    'billing_period_end': string;
    /**
     * 
     * @type {Array<CloudCostRowInput>}
     * @memberof ImportBatchRequest
     */
    'rows': Array<CloudCostRowInput>;
    /**
     * 
     * @type {string}
     * @memberof ImportBatchRequest
     */
    'reporting_currency'?: string;
}

