/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Reference to an invoice.
 * @export
 * @interface InvoiceReference
 */
export interface InvoiceReference {
    /**
     * The ID of the invoice.
     * @type {string}
     * @memberof InvoiceReference
     */
    'id': string;
    /**
     * The number of the invoice.
     * @type {string}
     * @memberof InvoiceReference
     */
    'number'?: string;
}

