/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LineTotal } from './line-total';
// May contain unused imports in some cases
// @ts-ignore
import type { Quantity } from './quantity';
// May contain unused imports in some cases
// @ts-ignore
import type { ReportingLineTotal } from './reporting-line-total';
// May contain unused imports in some cases
// @ts-ignore
import type { UnitCost } from './unit-cost';

/**
 * 
 * @export
 * @interface LineItemCreate
 */
export interface LineItemCreate {
    /**
     * 
     * @type {string}
     * @memberof LineItemCreate
     */
    'metric_type': string;
    /**
     * 
     * @type {Quantity}
     * @memberof LineItemCreate
     */
    'quantity': Quantity;
    /**
     * 
     * @type {string}
     * @memberof LineItemCreate
     */
    'unit': string;
    /**
     * 
     * @type {string}
     * @memberof LineItemCreate
     */
    'rate_snapshot_id'?: string;
    /**
     * 
     * @type {UnitCost}
     * @memberof LineItemCreate
     */
    'unit_cost': UnitCost;
    /**
     * 
     * @type {LineTotal}
     * @memberof LineItemCreate
     */
    'line_total': LineTotal;
    /**
     * 
     * @type {ReportingLineTotal}
     * @memberof LineItemCreate
     */
    'reporting_line_total': ReportingLineTotal;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof LineItemCreate
     */
    'metadata'?: { [key: string]: any; };
}

