/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FilterString } from './filter-string';
// May contain unused imports in some cases
// @ts-ignore
import type { WindowSize } from './window-size';

/**
 * A meter query request.
 * @export
 * @interface MeterQueryRequest
 */
export interface MeterQueryRequest {
    /**
     * Client ID Useful to track progress of a query.
     * @type {string}
     * @memberof MeterQueryRequest
     */
    'clientId'?: string;
    /**
     * Start date-time in RFC 3339 format.  Inclusive.
     * @type {string}
     * @memberof MeterQueryRequest
     */
    'from'?: string;
    /**
     * End date-time in RFC 3339 format.  Inclusive.
     * @type {string}
     * @memberof MeterQueryRequest
     */
    'to'?: string;
    /**
     * If not specified, a single usage aggregate will be returned for the entirety of the specified period for each subject and group.
     * @type {WindowSize}
     * @memberof MeterQueryRequest
     */
    'windowSize'?: WindowSize;
    /**
     * The value is the name of the time zone as defined in the IANA Time Zone Database (http://www.iana.org/time-zones). If not specified, the UTC timezone will be used.
     * @type {string}
     * @memberof MeterQueryRequest
     */
    'windowTimeZone'?: string;
    /**
     * Filtering by multiple subjects.
     * @type {Array<string>}
     * @memberof MeterQueryRequest
     */
    'subject'?: Array<string>;
    /**
     * Filtering by multiple customers.
     * @type {Array<string>}
     * @memberof MeterQueryRequest
     */
    'filterCustomerId'?: Array<string>;
    /**
     * Simple filter for group bys with exact match.
     * @type {{ [key: string]: Array<string>; }}
     * @memberof MeterQueryRequest
     */
    'filterGroupBy'?: { [key: string]: Array<string>; };
    /**
     * Optional advanced meter group by filters. You can use this to filter for values of the meter groupBy fields.
     * @type {{ [key: string]: FilterString; }}
     * @memberof MeterQueryRequest
     */
    'advancedMeterGroupByFilters'?: { [key: string]: FilterString; };
    /**
     * If not specified a single aggregate will be returned for each subject and time window. `subject` is a reserved group by value.
     * @type {Array<string>}
     * @memberof MeterQueryRequest
     */
    'groupBy'?: Array<string>;
}



