/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.0.0-rc6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { NotificationRuleBalanceThresholdCreateRequest } from './notification-rule-balance-threshold-create-request';
// May contain unused imports in some cases
// @ts-ignore
import type { NotificationRuleBalanceThresholdValue } from './notification-rule-balance-threshold-value';
// May contain unused imports in some cases
// @ts-ignore
import type { NotificationRuleEntitlementResetCreateRequest } from './notification-rule-entitlement-reset-create-request';
// May contain unused imports in some cases
// @ts-ignore
import type { NotificationRuleInvoiceCreatedCreateRequest } from './notification-rule-invoice-created-create-request';
// May contain unused imports in some cases
// @ts-ignore
import type { NotificationRuleInvoiceUpdatedCreateRequest } from './notification-rule-invoice-updated-create-request';

/**
 * @type NotificationRuleCreateRequest
 * Union type for requests creating new notification rule with certain type.
 * @export
 */
export type NotificationRuleCreateRequest = { type: 'entitlements.balance.threshold' } & NotificationRuleBalanceThresholdCreateRequest | { type: 'entitlements.reset' } & NotificationRuleEntitlementResetCreateRequest | { type: 'invoice.created' } & NotificationRuleInvoiceCreatedCreateRequest | { type: 'invoice.updated' } & NotificationRuleInvoiceUpdatedCreateRequest;


