/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.0.0-rc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Invoice } from './invoice';
// May contain unused imports in some cases
// @ts-ignore
import type { NotificationEventBalanceThresholdPayload } from './notification-event-balance-threshold-payload';
// May contain unused imports in some cases
// @ts-ignore
import type { NotificationEventInvoiceCreatedPayload } from './notification-event-invoice-created-payload';
// May contain unused imports in some cases
// @ts-ignore
import type { NotificationEventInvoiceUpdatedPayload } from './notification-event-invoice-updated-payload';
// May contain unused imports in some cases
// @ts-ignore
import type { NotificationEventResetPayload } from './notification-event-reset-payload';

/**
 * @type NotificationEventPayload
 * The delivery status of the notification event.
 * @export
 */
export type NotificationEventPayload = { type: 'entitlements.balance.threshold' } & NotificationEventBalanceThresholdPayload | { type: 'entitlements.reset' } & NotificationEventResetPayload | { type: 'invoice.created' } & NotificationEventInvoiceCreatedPayload | { type: 'invoice.updated' } & NotificationEventInvoiceUpdatedPayload;


