/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Order by options for notification channels.
 * @export
 * @enum {string}
 */

export const NotificationEventOrderBy = {
    Id: 'id',
    CreatedAt: 'createdAt'
} as const;

export type NotificationEventOrderBy = typeof NotificationEventOrderBy[keyof typeof NotificationEventOrderBy];



