/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Customer } from './customer';
// May contain unused imports in some cases
// @ts-ignore
import type { EntitlementMetered } from './entitlement-metered';
// May contain unused imports in some cases
// @ts-ignore
import type { EntitlementValue } from './entitlement-value';
// May contain unused imports in some cases
// @ts-ignore
import type { Feature } from './feature';
// May contain unused imports in some cases
// @ts-ignore
import type { NotificationRuleBalanceThresholdValue } from './notification-rule-balance-threshold-value';
// May contain unused imports in some cases
// @ts-ignore
import type { Subject } from './subject';

/**
 * Data of the payload for notification event with `entitlements.balance.threshold` type.
 * @export
 * @interface NotificationEventBalanceThresholdPayloadData
 */
export interface NotificationEventBalanceThresholdPayloadData {
    /**
     * 
     * @type {EntitlementMetered}
     * @memberof NotificationEventBalanceThresholdPayloadData
     */
    'entitlement': EntitlementMetered;
    /**
     * 
     * @type {Feature}
     * @memberof NotificationEventBalanceThresholdPayloadData
     */
    'feature': Feature;
    /**
     * 
     * @type {Subject}
     * @memberof NotificationEventBalanceThresholdPayloadData
     */
    'subject': Subject;
    /**
     * 
     * @type {EntitlementValue}
     * @memberof NotificationEventBalanceThresholdPayloadData
     */
    'value': EntitlementValue;
    /**
     * 
     * @type {Customer}
     * @memberof NotificationEventBalanceThresholdPayloadData
     */
    'customer'?: Customer;
    /**
     * 
     * @type {NotificationRuleBalanceThresholdValue}
     * @memberof NotificationEventBalanceThresholdPayloadData
     */
    'threshold': NotificationRuleBalanceThresholdValue;
}

