/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.0.0-rc6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { NotificationEventDeliveryStatus } from './notification-event-delivery-status';
// May contain unused imports in some cases
// @ts-ignore
import type { NotificationEventPayload } from './notification-event-payload';
// May contain unused imports in some cases
// @ts-ignore
import type { NotificationEventType } from './notification-event-type';
// May contain unused imports in some cases
// @ts-ignore
import type { NotificationRule } from './notification-rule';

/**
 * Type of the notification event.
 * @export
 * @interface NotificationEvent
 */
export interface NotificationEvent {
    /**
     * A unique identifier of the notification event.
     * @type {string}
     * @memberof NotificationEvent
     */
    'id': string;
    /**
     * Type of the notification event.
     * @type {NotificationEventType}
     * @memberof NotificationEvent
     */
    'type': NotificationEventType;
    /**
     * Timestamp when the notification event was created in RFC 3339 format.
     * @type {string}
     * @memberof NotificationEvent
     */
    'createdAt': string;
    /**
     * The nnotification rule which generated this event.
     * @type {NotificationRule}
     * @memberof NotificationEvent
     */
    'rule': NotificationRule;
    /**
     * The delivery status of the notification event.
     * @type {Array<NotificationEventDeliveryStatus>}
     * @memberof NotificationEvent
     */
    'deliveryStatus': Array<NotificationEventDeliveryStatus>;
    /**
     * Timestamp when the notification event was created in RFC 3339 format.
     * @type {NotificationEventPayload}
     * @memberof NotificationEvent
     */
    'payload': NotificationEventPayload;
    /**
     * Set of key-value pairs managed by the system. Cannot be modified by user.
     * @type {{ [key: string]: any; }}
     * @memberof NotificationEvent
     */
    'annotations'?: { [key: string]: any; };
}



