/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * POST /cases/open-from-scope — idempotent case creation.
 * @export
 * @interface OpenFromScopeRequest
 */
export interface OpenFromScopeRequest {
    /**
     * 
     * @type {string}
     * @memberof OpenFromScopeRequest
     */
    'account_id': string;
    /**
     * 
     * @type {string}
     * @memberof OpenFromScopeRequest
     */
    'customer_id': string;
    /**
     * 
     * @type {string}
     * @memberof OpenFromScopeRequest
     */
    'billing_account_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenFromScopeRequest
     */
    'bill_to_entity_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenFromScopeRequest
     */
    'currency_code'?: string;
    /**
     * Invoice IDs to attach
     * @type {Array<string>}
     * @memberof OpenFromScopeRequest
     */
    'invoice_ids'?: Array<string>;
}

