/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.0.0-rc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PaymentDueDate } from './payment-due-date';
// May contain unused imports in some cases
// @ts-ignore
import type { PaymentTermDueDate } from './payment-term-due-date';
// May contain unused imports in some cases
// @ts-ignore
import type { PaymentTermInstant } from './payment-term-instant';

/**
 * PaymentTerms defines the terms for payment.
 * @export
 * @interface PaymentTerms
 */
export interface PaymentTerms {
    /**
     * Type of terms to be applied.
     * @type {string}
     * @memberof PaymentTerms
     */
    'type': PaymentTermsTypeEnum;
    /**
     * Text detail of the chosen payment terms.
     * @type {string}
     * @memberof PaymentTerms
     */
    'detail'?: string;
    /**
     * Description of the conditions for payment.
     * @type {string}
     * @memberof PaymentTerms
     */
    'notes'?: string;
    /**
     * When the payment is due.
     * @type {Array<PaymentDueDate>}
     * @memberof PaymentTerms
     */
    'dueAt': Array<PaymentDueDate>;
}

export const PaymentTermsTypeEnum = {
    Instant: 'instant',
    DueDate: 'due_date'
} as const;

export type PaymentTermsTypeEnum = typeof PaymentTermsTypeEnum[keyof typeof PaymentTermsTypeEnum];


