/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A period with a start and end time.
 * @export
 * @interface Period
 */
export interface Period {
    /**
     * Period start time.
     * @type {string}
     * @memberof Period
     */
    'from': string;
    /**
     * Period end time.
     * @type {string}
     * @memberof Period
     */
    'to': string;
}

