/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.0.0-rc4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PlanAddon } from './plan-addon';

/**
 * Paginated response
 * @export
 * @interface PlanAddonPaginatedResponse
 */
export interface PlanAddonPaginatedResponse {
    /**
     * The total number of items.
     * @type {number}
     * @memberof PlanAddonPaginatedResponse
     */
    'totalCount': number;
    /**
     * The page index.
     * @type {number}
     * @memberof PlanAddonPaginatedResponse
     */
    'page': number;
    /**
     * The maximum number of items per page.
     * @type {number}
     * @memberof PlanAddonPaginatedResponse
     */
    'pageSize': number;
    /**
     * The items in the current page.
     * @type {Array<PlanAddon>}
     * @memberof PlanAddonPaginatedResponse
     */
    'items': Array<PlanAddon>;
}

