/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * References an exact plan.
 * @export
 * @interface PlanReference
 */
export interface PlanReference {
    /**
     * The plan ID.
     * @type {string}
     * @memberof PlanReference
     */
    'id': string;
    /**
     * The plan key.
     * @type {string}
     * @memberof PlanReference
     */
    'key': string;
    /**
     * The plan version.
     * @type {number}
     * @memberof PlanReference
     */
    'version': number;
}

