/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Pro-rating mode options for handling billing period changes.
 * @export
 * @enum {string}
 */

export const ProRatingMode = {
    ProratePrices: 'prorate_prices'
} as const;

export type ProRatingMode = typeof ProRatingMode[keyof typeof ProRatingMode];



