/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.3.0-rc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface QuoteRedlineResponse
 */
export interface QuoteRedlineResponse {
    /**
     * 
     * @type {string}
     * @memberof QuoteRedlineResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof QuoteRedlineResponse
     */
    'tenant_id': string;
    /**
     * 
     * @type {string}
     * @memberof QuoteRedlineResponse
     */
    'quote_id': string;
    /**
     * 
     * @type {number}
     * @memberof QuoteRedlineResponse
     */
    'quote_version': number;
    /**
     * 
     * @type {string}
     * @memberof QuoteRedlineResponse
     */
    'source': string;
    /**
     * 
     * @type {string}
     * @memberof QuoteRedlineResponse
     */
    'status': string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof QuoteRedlineResponse
     */
    'proposed_terms': { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof QuoteRedlineResponse
     */
    'redline_text': string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof QuoteRedlineResponse
     */
    'evidence_metadata': { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof QuoteRedlineResponse
     */
    'created_by_actor_type': string;
    /**
     * 
     * @type {string}
     * @memberof QuoteRedlineResponse
     */
    'created_by_actor_id': string;
    /**
     * 
     * @type {string}
     * @memberof QuoteRedlineResponse
     */
    'accepted_by_actor_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof QuoteRedlineResponse
     */
    'accepted_at'?: string;
    /**
     * 
     * @type {number}
     * @memberof QuoteRedlineResponse
     */
    'resulting_quote_version'?: number;
    /**
     * 
     * @type {string}
     * @memberof QuoteRedlineResponse
     */
    'created_at'?: string;
}

