/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.0.0-rc7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DynamicPriceWithCommitments } from './dynamic-price-with-commitments';
// May contain unused imports in some cases
// @ts-ignore
import type { FlatPriceWithPaymentTerm } from './flat-price-with-payment-term';
// May contain unused imports in some cases
// @ts-ignore
import type { PackagePriceWithCommitments } from './package-price-with-commitments';
// May contain unused imports in some cases
// @ts-ignore
import type { PricePaymentTerm } from './price-payment-term';
// May contain unused imports in some cases
// @ts-ignore
import type { PriceTier } from './price-tier';
// May contain unused imports in some cases
// @ts-ignore
import type { TieredPriceMode } from './tiered-price-mode';
// May contain unused imports in some cases
// @ts-ignore
import type { TieredPriceWithCommitments } from './tiered-price-with-commitments';
// May contain unused imports in some cases
// @ts-ignore
import type { UnitPriceWithCommitments } from './unit-price-with-commitments';

/**
 * @type RateCardUsageBasedPrice
 * The price of the usage based rate card.
 * @export
 */
export type RateCardUsageBasedPrice = { type: 'dynamic' } & DynamicPriceWithCommitments | { type: 'flat' } & FlatPriceWithPaymentTerm | { type: 'package' } & PackagePriceWithCommitments | { type: 'tiered' } & TieredPriceWithCommitments | { type: 'unit' } & UnitPriceWithCommitments;


