/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RatePerUnit } from './rate-per-unit';

/**
 * 
 * @export
 * @interface RateCatalogCreate
 */
export interface RateCatalogCreate {
    /**
     * 
     * @type {string}
     * @memberof RateCatalogCreate
     */
    'tenant_id': string;
    /**
     * 
     * @type {string}
     * @memberof RateCatalogCreate
     */
    'provider': string;
    /**
     * 
     * @type {string}
     * @memberof RateCatalogCreate
     */
    'model': string;
    /**
     * 
     * @type {string}
     * @memberof RateCatalogCreate
     */
    'metric_type': string;
    /**
     * 
     * @type {string}
     * @memberof RateCatalogCreate
     */
    'tier'?: string;
    /**
     * 
     * @type {RatePerUnit}
     * @memberof RateCatalogCreate
     */
    'rate_per_unit': RatePerUnit;
    /**
     * 
     * @type {number}
     * @memberof RateCatalogCreate
     */
    'rate_unit_scale'?: number;
    /**
     * 
     * @type {string}
     * @memberof RateCatalogCreate
     */
    'currency'?: string;
    /**
     * 
     * @type {string}
     * @memberof RateCatalogCreate
     */
    'source'?: string;
    /**
     * 
     * @type {string}
     * @memberof RateCatalogCreate
     */
    'source_ref'?: string;
    /**
     * 
     * @type {string}
     * @memberof RateCatalogCreate
     */
    'effective_from': string;
    /**
     * 
     * @type {string}
     * @memberof RateCatalogCreate
     */
    'effective_to'?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof RateCatalogCreate
     */
    'pricing_rules'?: { [key: string]: any; };
}

