/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReconciliationBasisOut
 */
export interface ReconciliationBasisOut {
    /**
     * 
     * @type {string}
     * @memberof ReconciliationBasisOut
     */
    'grade': string;
    /**
     * 
     * @type {string}
     * @memberof ReconciliationBasisOut
     */
    'data_freshness': string;
    /**
     * 
     * @type {number}
     * @memberof ReconciliationBasisOut
     */
    'cost_completeness_pct': number;
    /**
     * 
     * @type {string}
     * @memberof ReconciliationBasisOut
     */
    'observation_status': string;
    /**
     * 
     * @type {string}
     * @memberof ReconciliationBasisOut
     */
    'bom_approved_at': string;
}

