/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReconcileRequest
 */
export interface ReconcileRequest {
    /**
     * Deprecated. Tenant is derived from API key. If provided, must match authenticated tenant.
     * @type {string}
     * @memberof ReconcileRequest
     */
    'tenant_id'?: string;
    /**
     * Specific cost_event IDs to reconcile. If omitted, runs full pass.
     * @type {Array<string>}
     * @memberof ReconcileRequest
     */
    'cost_event_ids'?: Array<string>;
}

