/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.1.0-rc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RecurringPeriodInterval } from './recurring-period-interval';

/**
 * Recurring period with an interval and an anchor.
 * @export
 * @interface RecurringPeriodV2
 */
export interface RecurringPeriodV2 {
    /**
     * The unit of time for the interval. Heuristically maps ISO duraitons to enum values or returns the ISO duration.
     * @type {RecurringPeriodInterval}
     * @memberof RecurringPeriodV2
     */
    'interval': RecurringPeriodInterval;
    /**
     * A date-time anchor to base the recurring period on.
     * @type {string}
     * @memberof RecurringPeriodV2
     */
    'anchor': string;
}

