/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.0.0-rc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AppStatus } from './app-status';
// May contain unused imports in some cases
// @ts-ignore
import type { MarketplaceListing } from './marketplace-listing';

/**
 * Sandbox app can be used for testing OpenMeter features.  The app is not creating anything in external systems, thus it is safe to use for verifying OpenMeter features.
 * @export
 * @interface SandboxApp
 */
export interface SandboxApp {
    /**
     * A unique identifier for the resource.
     * @type {string}
     * @memberof SandboxApp
     */
    'id': string;
    /**
     * Human-readable name for the resource. Between 1 and 256 characters.
     * @type {string}
     * @memberof SandboxApp
     */
    'name': string;
    /**
     * Optional description of the resource. Maximum 1024 characters.
     * @type {string}
     * @memberof SandboxApp
     */
    'description'?: string;
    /**
     * Additional metadata for the resource.
     * @type {{ [key: string]: string; }}
     * @memberof SandboxApp
     */
    'metadata'?: { [key: string]: string; };
    /**
     * Timestamp of when the resource was created.
     * @type {string}
     * @memberof SandboxApp
     */
    'createdAt': string;
    /**
     * Timestamp of when the resource was last updated.
     * @type {string}
     * @memberof SandboxApp
     */
    'updatedAt': string;
    /**
     * Timestamp of when the resource was permanently deleted.
     * @type {string}
     * @memberof SandboxApp
     */
    'deletedAt'?: string;
    /**
     * The marketplace listing that this installed app is based on.
     * @type {MarketplaceListing}
     * @memberof SandboxApp
     */
    'listing': MarketplaceListing;
    /**
     * Status of the app connection.
     * @type {AppStatus}
     * @memberof SandboxApp
     */
    'status': AppStatus;
    /**
     * The app\'s type is Sandbox.
     * @type {string}
     * @memberof SandboxApp
     */
    'type': SandboxAppTypeEnum;
}

export const SandboxAppTypeEnum = {
    Sandbox: 'sandbox'
} as const;

export type SandboxAppTypeEnum = typeof SandboxAppTypeEnum[keyof typeof SandboxAppTypeEnum];


