/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SenderResponse
 */
export interface SenderResponse {
    /**
     * 
     * @type {string}
     * @memberof SenderResponse
     */
    'sender_name': string;
    /**
     * 
     * @type {string}
     * @memberof SenderResponse
     */
    'from_address': string;
    /**
     * 
     * @type {string}
     * @memberof SenderResponse
     */
    'reply_to': string;
    /**
     * 
     * @type {string}
     * @memberof SenderResponse
     */
    'support_contact': string;
}

