/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Response from creating a balance snapshot.
 * @export
 * @interface SnapshotResponse
 */
export interface SnapshotResponse {
    /**
     * 
     * @type {string}
     * @memberof SnapshotResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof SnapshotResponse
     */
    'tenant_id': string;
    /**
     * 
     * @type {string}
     * @memberof SnapshotResponse
     */
    'pool_id': string;
    /**
     * 
     * @type {string}
     * @memberof SnapshotResponse
     */
    'wallet_id': string;
    /**
     * 
     * @type {string}
     * @memberof SnapshotResponse
     */
    'as_of_effective_at': string;
    /**
     * 
     * @type {string}
     * @memberof SnapshotResponse
     */
    'as_of_recorded_at': string;
    /**
     * 
     * @type {number}
     * @memberof SnapshotResponse
     */
    'balance_micros': number;
    /**
     * 
     * @type {string}
     * @memberof SnapshotResponse
     */
    'snapshot_fingerprint': string;
    /**
     * 
     * @type {string}
     * @memberof SnapshotResponse
     */
    'created_at': string;
}

