/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StripeWebhookEventData } from './stripe-webhook-event-data';

/**
 * Stripe webhook event.
 * @export
 * @interface StripeWebhookEvent
 */
export interface StripeWebhookEvent {
    /**
     * The event ID.
     * @type {string}
     * @memberof StripeWebhookEvent
     */
    'id': string;
    /**
     * The event type.
     * @type {string}
     * @memberof StripeWebhookEvent
     */
    'type': string;
    /**
     * Live mode.
     * @type {boolean}
     * @memberof StripeWebhookEvent
     */
    'livemode': boolean;
    /**
     * The event created timestamp.
     * @type {number}
     * @memberof StripeWebhookEvent
     */
    'created': number;
    /**
     * 
     * @type {StripeWebhookEventData}
     * @memberof StripeWebhookEvent
     */
    'data': StripeWebhookEventData;
}

