/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.0.0-rc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SubscriptionErrorExtensions } from './subscription-error-extensions';

/**
 * The request could not be completed due to a conflict with the current state of the target resource. Variants with ErrorExtensions specific to subscriptions.
 * @export
 * @interface SubscriptionConflictErrorResponse
 */
export interface SubscriptionConflictErrorResponse {
    /**
     * Type contains a URI that identifies the problem type.
     * @type {string}
     * @memberof SubscriptionConflictErrorResponse
     */
    'type': string;
    /**
     * A a short, human-readable summary of the problem type.
     * @type {string}
     * @memberof SubscriptionConflictErrorResponse
     */
    'title': string;
    /**
     * The HTTP status code generated by the origin server for this occurrence of the problem.
     * @type {number}
     * @memberof SubscriptionConflictErrorResponse
     */
    'status'?: number;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     * @type {string}
     * @memberof SubscriptionConflictErrorResponse
     */
    'detail': string;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     * @type {string}
     * @memberof SubscriptionConflictErrorResponse
     */
    'instance': string;
    /**
     * Additional properties specific to the problem type may be present.
     * @type {SubscriptionErrorExtensions}
     * @memberof SubscriptionConflictErrorResponse
     */
    'extensions'?: SubscriptionErrorExtensions;
}

