/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.1.0-rc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EditSubscriptionAddItem } from './edit-subscription-add-item';
// May contain unused imports in some cases
// @ts-ignore
import type { EditSubscriptionAddPhase } from './edit-subscription-add-phase';
// May contain unused imports in some cases
// @ts-ignore
import type { EditSubscriptionRemoveItem } from './edit-subscription-remove-item';
// May contain unused imports in some cases
// @ts-ignore
import type { EditSubscriptionRemovePhase } from './edit-subscription-remove-phase';
// May contain unused imports in some cases
// @ts-ignore
import type { EditSubscriptionStretchPhase } from './edit-subscription-stretch-phase';
// May contain unused imports in some cases
// @ts-ignore
import type { EditSubscriptionUnscheduleEdit } from './edit-subscription-unschedule-edit';
// May contain unused imports in some cases
// @ts-ignore
import type { RateCard } from './rate-card';
// May contain unused imports in some cases
// @ts-ignore
import type { RemovePhaseShifting } from './remove-phase-shifting';
// May contain unused imports in some cases
// @ts-ignore
import type { SubscriptionPhaseCreate } from './subscription-phase-create';

/**
 * @type SubscriptionEditOperation
 * The operation to be performed on the subscription.
 * @export
 */
export type SubscriptionEditOperation = { op: 'add_item' } & EditSubscriptionAddItem | { op: 'add_phase' } & EditSubscriptionAddPhase | { op: 'remove_item' } & EditSubscriptionRemoveItem | { op: 'remove_phase' } & EditSubscriptionRemovePhase | { op: 'stretch_phase' } & EditSubscriptionStretchPhase | { op: 'unschedule_edit' } & EditSubscriptionUnscheduleEdit;


