/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Entitlement } from './entitlement';
// May contain unused imports in some cases
// @ts-ignore
import type { Feature } from './feature';

/**
 * Included contents like Entitlement, or the Feature.
 * @export
 * @interface SubscriptionItemIncluded
 */
export interface SubscriptionItemIncluded {
    /**
     * The feature the customer is entitled to use.
     * @type {Feature}
     * @memberof SubscriptionItemIncluded
     */
    'feature': Feature;
    /**
     * The entitlement of the Subscription Item.
     * @type {Entitlement}
     * @memberof SubscriptionItemIncluded
     */
    'entitlement'?: Entitlement;
}

