/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK covering billing (CLS) and usage (Meter) operations. Both surfaces share one client and one auth flow.
 *
 * The version of the OpenAPI document: 0.1.0-rc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Alignment } from './alignment';
// May contain unused imports in some cases
// @ts-ignore
import type { CommercialOverrides } from './commercial-overrides';
// May contain unused imports in some cases
// @ts-ignore
import type { PlanReference } from './plan-reference';
// May contain unused imports in some cases
// @ts-ignore
import type { ProRatingConfig } from './pro-rating-config';
// May contain unused imports in some cases
// @ts-ignore
import type { SubscriptionStatus } from './subscription-status';

/**
 * Subscription is an exact subscription instance.
 * @export
 * @interface Subscription
 */
export interface Subscription {
    /**
     * A unique identifier for the resource.
     * @type {string}
     * @memberof Subscription
     */
    'id': string;
    /**
     * Human-readable name for the resource. Between 1 and 256 characters.
     * @type {string}
     * @memberof Subscription
     */
    'name': string;
    /**
     * Optional description of the resource. Maximum 1024 characters.
     * @type {string}
     * @memberof Subscription
     */
    'description'?: string;
    /**
     * Additional metadata for the resource.
     * @type {{ [key: string]: string; }}
     * @memberof Subscription
     */
    'metadata'?: { [key: string]: string; };
    /**
     * Timestamp of when the resource was created.
     * @type {string}
     * @memberof Subscription
     */
    'createdAt': string;
    /**
     * Timestamp of when the resource was last updated.
     * @type {string}
     * @memberof Subscription
     */
    'updatedAt': string;
    /**
     * Timestamp of when the resource was permanently deleted.
     * @type {string}
     * @memberof Subscription
     */
    'deletedAt'?: string;
    /**
     * The cadence start of the resource.
     * @type {string}
     * @memberof Subscription
     */
    'activeFrom': string;
    /**
     * The cadence end of the resource.
     * @type {string}
     * @memberof Subscription
     */
    'activeTo'?: string;
    /**
     * Set of key-value pairs managed by the system. Cannot be modified by user.
     * @type {{ [key: string]: any; }}
     * @memberof Subscription
     */
    'annotations'?: { [key: string]: any; };
    /**
     * Alignment configuration for the plan.
     * @type {Alignment}
     * @memberof Subscription
     * @deprecated
     */
    'alignment'?: Alignment;
    /**
     * The status of the subscription.
     * @type {SubscriptionStatus}
     * @memberof Subscription
     */
    'status': SubscriptionStatus;
    /**
     * The customer ID of the subscription.
     * @type {string}
     * @memberof Subscription
     */
    'customerId': string;
    /**
     * The plan of the subscription.
     * @type {PlanReference}
     * @memberof Subscription
     */
    'plan'?: PlanReference;
    /**
     * The currency code of the subscription. Will be revised once we add multi currency support.
     * @type {string}
     * @memberof Subscription
     */
    'currency': string;
    /**
     * The billing cadence for the subscriptions. Defines how often customers are billed using ISO8601 duration format. Examples: \"P1M\" (monthly), \"P3M\" (quarterly), \"P1Y\" (annually).
     * @type {string}
     * @memberof Subscription
     */
    'billingCadence': string;
    /**
     * The pro-rating configuration for the subscriptions.
     * @type {ProRatingConfig}
     * @memberof Subscription
     */
    'proRatingConfig'?: ProRatingConfig;
    /**
     * The normalizedbilling anchor of the subscription.
     * @type {string}
     * @memberof Subscription
     */
    'billingAnchor': string;
    /**
     * Commercial terms for this subscription (discounts, pool overrides, wallet policy).
     * @type {CommercialOverrides}
     * @memberof Subscription
     */
    'commercialOverrides'?: CommercialOverrides;
}



