/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.2.0-rc3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Tax behavior.  This enum is used to specify whether tax is included in the price or excluded from the price.
 * @export
 * @enum {string}
 */

export const TaxBehavior = {
    Inclusive: 'inclusive',
    Exclusive: 'exclusive'
} as const;

export type TaxBehavior = typeof TaxBehavior[keyof typeof TaxBehavior];



