/* tslint:disable */
/* eslint-disable */
/**
 * Moolabs API
 * Unified Moolabs SDK. Capability-based public surface stitched from internal service specs: bff, meter, arc, acute. Customers see capability namespaces (usage, billing, collections, etc.); the SDK routes per-operation internally.
 *
 * The version of the OpenAPI document: 0.3.0-rc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ValidateTemplateRequest
 */
export interface ValidateTemplateRequest {
    /**
     * 
     * @type {string}
     * @memberof ValidateTemplateRequest
     */
    'channel'?: ValidateTemplateRequestChannelEnum;
    /**
     * 
     * @type {string}
     * @memberof ValidateTemplateRequest
     */
    'subject_template': string;
    /**
     * 
     * @type {string}
     * @memberof ValidateTemplateRequest
     */
    'body_template': string;
    /**
     * 
     * @type {string}
     * @memberof ValidateTemplateRequest
     */
    'preview_mode'?: ValidateTemplateRequestPreviewModeEnum;
    /**
     * 
     * @type {string}
     * @memberof ValidateTemplateRequest
     */
    'case_id'?: string;
}

export const ValidateTemplateRequestChannelEnum = {
    Email: 'email'
} as const;

export type ValidateTemplateRequestChannelEnum = typeof ValidateTemplateRequestChannelEnum[keyof typeof ValidateTemplateRequestChannelEnum];
export const ValidateTemplateRequestPreviewModeEnum = {
    Sample: 'sample',
    RealCase: 'real_case'
} as const;

export type ValidateTemplateRequestPreviewModeEnum = typeof ValidateTemplateRequestPreviewModeEnum[keyof typeof ValidateTemplateRequestPreviewModeEnum];


